// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module restoration_top_restoration_top_Pipeline_VITIS_LOOP_320_1_VITIS_LOOP_322_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        zext_ln887,
        zext_ln889,
        input_r,
        tile_a_address0,
        tile_a_ce0,
        tile_a_we0,
        tile_a_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [7:0] m_axi_gmem0_0_WDATA;
output  [0:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [7:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [10:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [6:0] zext_ln887;
input  [6:0] zext_ln889;
input  [63:0] input_r;
output  [16:0] tile_a_address0;
output   tile_a_ce0;
output   tile_a_we0;
output  [7:0] tile_a_d0;

reg ap_idle;
reg m_axi_gmem0_0_ARVALID;
reg m_axi_gmem0_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln320_reg_419;
reg   [0:0] icmp_ln320_reg_419_pp0_iter2_reg;
reg   [0:0] icmp_ln333_reg_438;
reg    ap_predicate_op70_readreq_state4;
reg    ap_block_state4_io;
reg   [0:0] icmp_ln320_reg_419_pp0_iter10_reg;
reg   [0:0] icmp_ln333_reg_438_pp0_iter10_reg;
reg    ap_predicate_op78_read_state12;
reg    ap_block_state12_pp0_stage0_iter11;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln320_fu_193_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_AR;
wire    ap_block_pp0_stage0;
reg    gmem0_blk_n_R;
reg    ap_block_pp0_stage0_11001;
wire   [8:0] zext_ln889_cast_fu_167_p1;
reg   [8:0] zext_ln889_cast_reg_409;
wire   [8:0] zext_ln887_cast_fu_171_p1;
reg   [8:0] zext_ln887_cast_reg_414;
reg   [0:0] icmp_ln320_reg_419_pp0_iter1_reg;
reg   [0:0] icmp_ln320_reg_419_pp0_iter3_reg;
reg   [0:0] icmp_ln320_reg_419_pp0_iter4_reg;
reg   [0:0] icmp_ln320_reg_419_pp0_iter5_reg;
reg   [0:0] icmp_ln320_reg_419_pp0_iter6_reg;
reg   [0:0] icmp_ln320_reg_419_pp0_iter7_reg;
reg   [0:0] icmp_ln320_reg_419_pp0_iter8_reg;
reg   [0:0] icmp_ln320_reg_419_pp0_iter9_reg;
reg   [0:0] icmp_ln320_reg_419_pp0_iter11_reg;
wire   [5:0] add_ln325_fu_244_p2;
reg   [5:0] add_ln325_reg_423;
wire   [5:0] add_ln328_fu_276_p2;
reg   [5:0] add_ln328_reg_428;
wire   [10:0] add_ln310_fu_286_p2;
reg   [10:0] add_ln310_reg_433;
reg   [10:0] add_ln310_reg_433_pp0_iter2_reg;
reg   [10:0] add_ln310_reg_433_pp0_iter3_reg;
reg   [10:0] add_ln310_reg_433_pp0_iter4_reg;
reg   [10:0] add_ln310_reg_433_pp0_iter5_reg;
reg   [10:0] add_ln310_reg_433_pp0_iter6_reg;
reg   [10:0] add_ln310_reg_433_pp0_iter7_reg;
reg   [10:0] add_ln310_reg_433_pp0_iter8_reg;
reg   [10:0] add_ln310_reg_433_pp0_iter9_reg;
reg   [10:0] add_ln310_reg_433_pp0_iter10_reg;
reg   [10:0] add_ln310_reg_433_pp0_iter11_reg;
wire   [0:0] icmp_ln333_fu_356_p2;
reg   [0:0] icmp_ln333_reg_438_pp0_iter3_reg;
reg   [0:0] icmp_ln333_reg_438_pp0_iter4_reg;
reg   [0:0] icmp_ln333_reg_438_pp0_iter5_reg;
reg   [0:0] icmp_ln333_reg_438_pp0_iter6_reg;
reg   [0:0] icmp_ln333_reg_438_pp0_iter7_reg;
reg   [0:0] icmp_ln333_reg_438_pp0_iter8_reg;
reg   [0:0] icmp_ln333_reg_438_pp0_iter9_reg;
reg   [0:0] icmp_ln333_reg_438_pp0_iter11_reg;
reg   [63:0] gmem0_addr_reg_442;
reg   [7:0] value_reg_448;
reg   [7:0] ap_phi_mux_value_1_phi_fu_159_p4;
reg   [7:0] ap_phi_reg_pp0_iter12_value_1_reg_155;
wire   [7:0] ap_phi_reg_pp0_iter0_value_1_reg_155;
reg   [7:0] ap_phi_reg_pp0_iter1_value_1_reg_155;
reg   [7:0] ap_phi_reg_pp0_iter2_value_1_reg_155;
reg   [7:0] ap_phi_reg_pp0_iter3_value_1_reg_155;
reg   [7:0] ap_phi_reg_pp0_iter4_value_1_reg_155;
reg   [7:0] ap_phi_reg_pp0_iter5_value_1_reg_155;
reg   [7:0] ap_phi_reg_pp0_iter6_value_1_reg_155;
reg   [7:0] ap_phi_reg_pp0_iter7_value_1_reg_155;
reg   [7:0] ap_phi_reg_pp0_iter8_value_1_reg_155;
reg   [7:0] ap_phi_reg_pp0_iter9_value_1_reg_155;
reg   [7:0] ap_phi_reg_pp0_iter10_value_1_reg_155;
reg   [7:0] ap_phi_reg_pp0_iter11_value_1_reg_155;
wire   [63:0] zext_ln342_fu_379_p1;
wire   [63:0] add_ln339_1_fu_367_p2;
reg   [5:0] x_1_fu_100;
wire   [5:0] add_ln322_fu_292_p2;
wire    ap_loop_init;
reg   [5:0] y_fu_104;
wire   [5:0] select_ln320_1_fu_236_p3;
reg   [10:0] indvar_flatten_fu_108;
wire   [10:0] add_ln320_fu_199_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten_load;
reg    tile_a_we0_local;
reg    tile_a_ce0_local;
wire   [0:0] icmp_ln322_fu_216_p2;
wire   [5:0] add_ln320_1_fu_230_p2;
wire   [8:0] tmp_fu_258_p3;
wire   [10:0] p_shl_fu_250_p3;
wire   [10:0] zext_ln339_fu_266_p1;
wire   [5:0] select_ln320_fu_222_p3;
wire   [10:0] zext_ln305_fu_282_p1;
wire   [10:0] add_ln339_2_fu_270_p2;
wire  signed [8:0] sext_ln325_fu_308_p1;
wire   [8:0] add_ln325_1_fu_311_p2;
wire   [15:0] shl_ln_fu_316_p3;
wire  signed [8:0] sext_ln328_fu_328_p1;
wire  signed [8:0] add_ln328_1_fu_331_p2;
wire   [8:0] or_ln333_fu_340_p2;
wire   [1:0] tmp_1_fu_346_p4;
wire  signed [63:0] sext_ln333_1_fu_336_p1;
wire   [63:0] add_ln339_fu_362_p2;
wire  signed [63:0] sext_ln333_fu_324_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 x_1_fu_100 = 6'd0;
#0 y_fu_104 = 6'd0;
#0 indvar_flatten_fu_108 = 11'd0;
#0 ap_done_reg = 1'b0;
end

restoration_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln333_fu_356_p2 == 1'd0) & (icmp_ln320_reg_419_pp0_iter1_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter3_value_1_reg_155 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_value_1_reg_155 <= ap_phi_reg_pp0_iter2_value_1_reg_155;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln320_fu_193_p2 == 1'd0))) begin
            indvar_flatten_fu_108 <= add_ln320_fu_199_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_108 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_1_fu_100 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            x_1_fu_100 <= add_ln322_fu_292_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            y_fu_104 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            y_fu_104 <= select_ln320_1_fu_236_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln310_reg_433 <= add_ln310_fu_286_p2;
        add_ln325_reg_423 <= add_ln325_fu_244_p2;
        add_ln328_reg_428 <= add_ln328_fu_276_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln320_reg_419 <= icmp_ln320_fu_193_p2;
        icmp_ln320_reg_419_pp0_iter1_reg <= icmp_ln320_reg_419;
        zext_ln887_cast_reg_414[6 : 0] <= zext_ln887_cast_fu_171_p1[6 : 0];
        zext_ln889_cast_reg_409[6 : 0] <= zext_ln889_cast_fu_167_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln310_reg_433_pp0_iter10_reg <= add_ln310_reg_433_pp0_iter9_reg;
        add_ln310_reg_433_pp0_iter11_reg <= add_ln310_reg_433_pp0_iter10_reg;
        add_ln310_reg_433_pp0_iter2_reg <= add_ln310_reg_433;
        add_ln310_reg_433_pp0_iter3_reg <= add_ln310_reg_433_pp0_iter2_reg;
        add_ln310_reg_433_pp0_iter4_reg <= add_ln310_reg_433_pp0_iter3_reg;
        add_ln310_reg_433_pp0_iter5_reg <= add_ln310_reg_433_pp0_iter4_reg;
        add_ln310_reg_433_pp0_iter6_reg <= add_ln310_reg_433_pp0_iter5_reg;
        add_ln310_reg_433_pp0_iter7_reg <= add_ln310_reg_433_pp0_iter6_reg;
        add_ln310_reg_433_pp0_iter8_reg <= add_ln310_reg_433_pp0_iter7_reg;
        add_ln310_reg_433_pp0_iter9_reg <= add_ln310_reg_433_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        gmem0_addr_reg_442 <= add_ln339_1_fu_367_p2;
        icmp_ln320_reg_419_pp0_iter10_reg <= icmp_ln320_reg_419_pp0_iter9_reg;
        icmp_ln320_reg_419_pp0_iter11_reg <= icmp_ln320_reg_419_pp0_iter10_reg;
        icmp_ln320_reg_419_pp0_iter2_reg <= icmp_ln320_reg_419_pp0_iter1_reg;
        icmp_ln320_reg_419_pp0_iter3_reg <= icmp_ln320_reg_419_pp0_iter2_reg;
        icmp_ln320_reg_419_pp0_iter4_reg <= icmp_ln320_reg_419_pp0_iter3_reg;
        icmp_ln320_reg_419_pp0_iter5_reg <= icmp_ln320_reg_419_pp0_iter4_reg;
        icmp_ln320_reg_419_pp0_iter6_reg <= icmp_ln320_reg_419_pp0_iter5_reg;
        icmp_ln320_reg_419_pp0_iter7_reg <= icmp_ln320_reg_419_pp0_iter6_reg;
        icmp_ln320_reg_419_pp0_iter8_reg <= icmp_ln320_reg_419_pp0_iter7_reg;
        icmp_ln320_reg_419_pp0_iter9_reg <= icmp_ln320_reg_419_pp0_iter8_reg;
        icmp_ln333_reg_438 <= icmp_ln333_fu_356_p2;
        icmp_ln333_reg_438_pp0_iter10_reg <= icmp_ln333_reg_438_pp0_iter9_reg;
        icmp_ln333_reg_438_pp0_iter11_reg <= icmp_ln333_reg_438_pp0_iter10_reg;
        icmp_ln333_reg_438_pp0_iter3_reg <= icmp_ln333_reg_438;
        icmp_ln333_reg_438_pp0_iter4_reg <= icmp_ln333_reg_438_pp0_iter3_reg;
        icmp_ln333_reg_438_pp0_iter5_reg <= icmp_ln333_reg_438_pp0_iter4_reg;
        icmp_ln333_reg_438_pp0_iter6_reg <= icmp_ln333_reg_438_pp0_iter5_reg;
        icmp_ln333_reg_438_pp0_iter7_reg <= icmp_ln333_reg_438_pp0_iter6_reg;
        icmp_ln333_reg_438_pp0_iter8_reg <= icmp_ln333_reg_438_pp0_iter7_reg;
        icmp_ln333_reg_438_pp0_iter9_reg <= icmp_ln333_reg_438_pp0_iter8_reg;
        value_reg_448 <= m_axi_gmem0_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter10_value_1_reg_155 <= ap_phi_reg_pp0_iter9_value_1_reg_155;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter11_value_1_reg_155 <= ap_phi_reg_pp0_iter10_value_1_reg_155;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter12_value_1_reg_155 <= ap_phi_reg_pp0_iter11_value_1_reg_155;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_value_1_reg_155 <= ap_phi_reg_pp0_iter0_value_1_reg_155;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter2_value_1_reg_155 <= ap_phi_reg_pp0_iter1_value_1_reg_155;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter4_value_1_reg_155 <= ap_phi_reg_pp0_iter3_value_1_reg_155;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_value_1_reg_155 <= ap_phi_reg_pp0_iter4_value_1_reg_155;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_value_1_reg_155 <= ap_phi_reg_pp0_iter5_value_1_reg_155;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter7_value_1_reg_155 <= ap_phi_reg_pp0_iter6_value_1_reg_155;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter8_value_1_reg_155 <= ap_phi_reg_pp0_iter7_value_1_reg_155;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter9_value_1_reg_155 <= ap_phi_reg_pp0_iter8_value_1_reg_155;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln320_fu_193_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln333_reg_438_pp0_iter11_reg == 1'd1) & (icmp_ln320_reg_419_pp0_iter11_reg == 1'd0))) begin
        ap_phi_mux_value_1_phi_fu_159_p4 = value_reg_448;
    end else begin
        ap_phi_mux_value_1_phi_fu_159_p4 = ap_phi_reg_pp0_iter12_value_1_reg_155;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_108;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op70_readreq_state4 == 1'b1))) begin
        gmem0_blk_n_AR = m_axi_gmem0_0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op78_read_state12 == 1'b1))) begin
        gmem0_blk_n_R = m_axi_gmem0_0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op70_readreq_state4 == 1'b1))) begin
        m_axi_gmem0_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem0_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op78_read_state12 == 1'b1))) begin
        m_axi_gmem0_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tile_a_ce0_local = 1'b1;
    end else begin
        tile_a_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tile_a_we0_local = 1'b1;
    end else begin
        tile_a_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln310_fu_286_p2 = (zext_ln305_fu_282_p1 + add_ln339_2_fu_270_p2);

assign add_ln320_1_fu_230_p2 = (y_fu_104 + 6'd1);

assign add_ln320_fu_199_p2 = (ap_sig_allocacmp_indvar_flatten_load + 11'd1);

assign add_ln322_fu_292_p2 = (select_ln320_fu_222_p3 + 6'd1);

assign add_ln325_1_fu_311_p2 = ($signed(sext_ln325_fu_308_p1) + $signed(zext_ln887_cast_reg_414));

assign add_ln325_fu_244_p2 = ($signed(select_ln320_1_fu_236_p3) + $signed(6'd45));

assign add_ln328_1_fu_331_p2 = ($signed(sext_ln328_fu_328_p1) + $signed(zext_ln889_cast_reg_409));

assign add_ln328_fu_276_p2 = ($signed(select_ln320_fu_222_p3) + $signed(6'd45));

assign add_ln339_1_fu_367_p2 = ($signed(add_ln339_fu_362_p2) + $signed(sext_ln333_fu_324_p1));

assign add_ln339_2_fu_270_p2 = (p_shl_fu_250_p3 + zext_ln339_fu_266_p1);

assign add_ln339_fu_362_p2 = ($signed(sext_ln333_1_fu_336_p1) + $signed(input_r));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

always @ (*) begin
    ap_block_state12_pp0_stage0_iter11 = ((ap_predicate_op78_read_state12 == 1'b1) & (m_axi_gmem0_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state4_io = ((m_axi_gmem0_0_ARREADY == 1'b0) & (ap_predicate_op70_readreq_state4 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_value_1_reg_155 = 'bx;

always @ (*) begin
    ap_predicate_op70_readreq_state4 = ((icmp_ln333_reg_438 == 1'd1) & (icmp_ln320_reg_419_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op78_read_state12 = ((icmp_ln333_reg_438_pp0_iter10_reg == 1'd1) & (icmp_ln320_reg_419_pp0_iter10_reg == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign icmp_ln320_fu_193_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 11'd1600) ? 1'b1 : 1'b0);

assign icmp_ln322_fu_216_p2 = ((x_1_fu_100 == 6'd40) ? 1'b1 : 1'b0);

assign icmp_ln333_fu_356_p2 = ((tmp_1_fu_346_p4 == 2'd0) ? 1'b1 : 1'b0);

assign m_axi_gmem0_0_ARADDR = gmem0_addr_reg_442;

assign m_axi_gmem0_0_ARBURST = 2'd0;

assign m_axi_gmem0_0_ARCACHE = 4'd0;

assign m_axi_gmem0_0_ARID = 1'd0;

assign m_axi_gmem0_0_ARLEN = 64'd1;

assign m_axi_gmem0_0_ARLOCK = 2'd0;

assign m_axi_gmem0_0_ARPROT = 3'd0;

assign m_axi_gmem0_0_ARQOS = 4'd0;

assign m_axi_gmem0_0_ARREGION = 4'd0;

assign m_axi_gmem0_0_ARSIZE = 3'd0;

assign m_axi_gmem0_0_ARUSER = 1'd0;

assign m_axi_gmem0_0_AWADDR = 64'd0;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = 32'd0;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_AWVALID = 1'b0;

assign m_axi_gmem0_0_BREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = 8'd0;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 1'd0;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign m_axi_gmem0_0_WVALID = 1'b0;

assign or_ln333_fu_340_p2 = (add_ln328_1_fu_331_p2 | add_ln325_1_fu_311_p2);

assign p_shl_fu_250_p3 = {{select_ln320_1_fu_236_p3}, {5'd0}};

assign select_ln320_1_fu_236_p3 = ((icmp_ln322_fu_216_p2[0:0] == 1'b1) ? add_ln320_1_fu_230_p2 : y_fu_104);

assign select_ln320_fu_222_p3 = ((icmp_ln322_fu_216_p2[0:0] == 1'b1) ? 6'd0 : x_1_fu_100);

assign sext_ln325_fu_308_p1 = $signed(add_ln325_reg_423);

assign sext_ln328_fu_328_p1 = $signed(add_ln328_reg_428);

assign sext_ln333_1_fu_336_p1 = add_ln328_1_fu_331_p2;

assign sext_ln333_fu_324_p1 = $signed(shl_ln_fu_316_p3);

assign shl_ln_fu_316_p3 = {{add_ln325_1_fu_311_p2}, {7'd0}};

assign tile_a_address0 = zext_ln342_fu_379_p1;

assign tile_a_ce0 = tile_a_ce0_local;

assign tile_a_d0 = ap_phi_mux_value_1_phi_fu_159_p4;

assign tile_a_we0 = tile_a_we0_local;

assign tmp_1_fu_346_p4 = {{or_ln333_fu_340_p2[8:7]}};

assign tmp_fu_258_p3 = {{select_ln320_1_fu_236_p3}, {3'd0}};

assign zext_ln305_fu_282_p1 = select_ln320_fu_222_p3;

assign zext_ln339_fu_266_p1 = tmp_fu_258_p3;

assign zext_ln342_fu_379_p1 = add_ln310_reg_433_pp0_iter11_reg;

assign zext_ln887_cast_fu_171_p1 = zext_ln887;

assign zext_ln889_cast_fu_167_p1 = zext_ln889;

always @ (posedge ap_clk) begin
    zext_ln889_cast_reg_409[8:7] <= 2'b00;
    zext_ln887_cast_reg_414[8:7] <= 2'b00;
end

endmodule //restoration_top_restoration_top_Pipeline_VITIS_LOOP_320_1_VITIS_LOOP_322_2
