// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module restoration_top_residual_block_tiled_Pipeline_VITIS_LOOP_488_4_VITIS_LOOP_490_5_VITIS_LOOP_492_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        add_ln504_2,
        zext_ln310_7,
        zext_ln488,
        accumulator_2_out,
        accumulator_2_out_ap_vld,
        tile_a_address0,
        tile_a_ce0,
        tile_a_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [7:0] m_axi_gmem0_0_WDATA;
output  [0:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [7:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [10:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [63:0] add_ln504_2;
input  [5:0] zext_ln310_7;
input  [5:0] zext_ln488;
output  [23:0] accumulator_2_out;
output   accumulator_2_out_ap_vld;
output  [16:0] tile_a_address0;
output   tile_a_ce0;
input  [7:0] tile_a_q0;

reg ap_idle;
reg m_axi_gmem0_0_RREADY;
reg accumulator_2_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln488_fu_208_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_R;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [15:0] zext_ln488_cast_fu_167_p1;
reg   [15:0] zext_ln488_cast_reg_523;
wire   [10:0] zext_ln310_7_cast_fu_171_p1;
reg   [10:0] zext_ln310_7_cast_reg_528;
reg   [0:0] icmp_ln488_reg_533;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln488_reg_533_pp0_iter1_reg;
reg   [0:0] icmp_ln488_reg_533_pp0_iter2_reg;
reg   [0:0] icmp_ln488_reg_533_pp0_iter3_reg;
reg   [0:0] icmp_ln488_reg_533_pp0_iter4_reg;
reg   [0:0] icmp_ln488_reg_533_pp0_iter5_reg;
wire   [1:0] kx_mid2_fu_295_p3;
reg   [1:0] kx_mid2_reg_537;
reg   [1:0] kx_mid2_reg_537_pp0_iter2_reg;
wire   [1:0] select_ln490_fu_303_p3;
reg   [1:0] select_ln490_reg_542;
wire   [10:0] add_ln310_fu_339_p2;
reg   [10:0] add_ln310_reg_547;
wire   [15:0] add_ln492_1_fu_418_p2;
reg   [15:0] add_ln492_1_reg_552;
reg  signed [7:0] gmem0_addr_read_reg_562;
wire   [63:0] zext_ln495_fu_443_p1;
wire    ap_block_pp0_stage0_grp0;
reg   [23:0] accumulator_1_fu_100;
wire  signed [23:0] grp_fu_466_p3;
reg  signed [23:0] ap_sig_allocacmp_accumulator_1_load_1;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [1:0] kx_fu_104;
wire   [1:0] add_ln492_fu_345_p2;
reg   [1:0] ky_fu_108;
reg   [3:0] indvar_flatten_fu_112;
wire   [3:0] select_ln490_1_fu_357_p3;
reg   [5:0] ic_fu_116;
wire   [5:0] select_ln488_fu_275_p3;
reg   [8:0] indvar_flatten14_fu_120;
wire   [8:0] add_ln488_fu_214_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten14_load;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage0_01001_grp0;
reg    tile_a_ce0_local;
wire   [0:0] icmp_ln490_fu_237_p2;
wire   [0:0] icmp_ln492_fu_257_p2;
wire   [0:0] xor_ln486_fu_251_p2;
wire   [5:0] add_ln488_1_fu_269_p2;
wire   [1:0] select_ln486_fu_243_p3;
wire   [0:0] and_ln486_fu_263_p2;
wire   [0:0] empty_fu_289_p2;
wire   [1:0] add_ln490_fu_283_p2;
wire   [4:0] trunc_ln310_fu_311_p1;
wire   [9:0] tmp_fu_315_p3;
wire   [7:0] tmp_2_fu_327_p3;
wire   [10:0] zext_ln310_fu_323_p1;
wire   [10:0] zext_ln310_1_fu_335_p1;
wire   [3:0] add_ln490_1_fu_351_p2;
wire   [10:0] add_ln310_2_fu_385_p2;
wire   [10:0] zext_ln310_2_fu_389_p1;
wire   [10:0] add_ln310_3_fu_392_p2;
wire   [13:0] tmp_3_fu_406_p3;
wire   [15:0] p_shl_fu_398_p3;
wire   [15:0] zext_ln492_fu_414_p1;
wire   [15:0] add_ln310_4_fu_433_p2;
wire   [15:0] zext_ln304_fu_430_p1;
wire   [15:0] add_ln310_5_fu_437_p2;
reg    grp_fu_466_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_149;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 accumulator_1_fu_100 = 24'd0;
#0 kx_fu_104 = 2'd0;
#0 ky_fu_108 = 2'd0;
#0 indvar_flatten_fu_112 = 4'd0;
#0 ic_fu_116 = 6'd0;
#0 indvar_flatten14_fu_120 = 9'd0;
#0 ap_done_reg = 1'b0;
end

restoration_top_mac_muladd_8s_8s_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_8s_8s_24s_24_4_1_U59(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(gmem0_addr_read_reg_562),
    .din1(tile_a_q0),
    .din2(ap_sig_allocacmp_accumulator_1_load_1),
    .ce(grp_fu_466_ce),
    .dout(grp_fu_466_p3)
);

restoration_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            accumulator_1_fu_100 <= 24'd0;
        end else if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
            accumulator_1_fu_100 <= grp_fu_466_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_149)) begin
        if ((ap_loop_init == 1'b1)) begin
            ic_fu_116 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ic_fu_116 <= select_ln488_fu_275_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln488_fu_208_p2 == 1'd0))) begin
            indvar_flatten14_fu_120 <= add_ln488_fu_214_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten14_fu_120 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_149)) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_112 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            indvar_flatten_fu_112 <= select_ln490_1_fu_357_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_149)) begin
        if ((ap_loop_init == 1'b1)) begin
            kx_fu_104 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            kx_fu_104 <= add_ln492_fu_345_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_149)) begin
        if ((ap_loop_init == 1'b1)) begin
            ky_fu_108 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ky_fu_108 <= select_ln490_fu_303_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        add_ln310_reg_547[10 : 3] <= add_ln310_fu_339_p2[10 : 3];
        kx_mid2_reg_537 <= kx_mid2_fu_295_p3;
        select_ln490_reg_542 <= select_ln490_fu_303_p3;
        zext_ln310_7_cast_reg_528[5 : 0] <= zext_ln310_7_cast_fu_171_p1[5 : 0];
        zext_ln488_cast_reg_523[5 : 0] <= zext_ln488_cast_fu_167_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        add_ln492_1_reg_552[15 : 3] <= add_ln492_1_fu_418_p2[15 : 3];
        kx_mid2_reg_537_pp0_iter2_reg <= kx_mid2_reg_537;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln488_reg_533 <= icmp_ln488_fu_208_p2;
        icmp_ln488_reg_533_pp0_iter1_reg <= icmp_ln488_reg_533;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        icmp_ln488_reg_533_pp0_iter2_reg <= icmp_ln488_reg_533_pp0_iter1_reg;
        icmp_ln488_reg_533_pp0_iter3_reg <= icmp_ln488_reg_533_pp0_iter2_reg;
        icmp_ln488_reg_533_pp0_iter4_reg <= icmp_ln488_reg_533_pp0_iter3_reg;
        icmp_ln488_reg_533_pp0_iter5_reg <= icmp_ln488_reg_533_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        gmem0_addr_read_reg_562 <= m_axi_gmem0_0_RDATA;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln488_reg_533_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        accumulator_2_out_ap_vld = 1'b1;
    end else begin
        accumulator_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln488_fu_208_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp0))) begin
        ap_sig_allocacmp_accumulator_1_load_1 = grp_fu_466_p3;
    end else begin
        ap_sig_allocacmp_accumulator_1_load_1 = accumulator_1_fu_100;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten14_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten14_load = indvar_flatten14_fu_120;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem0_blk_n_R = m_axi_gmem0_0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        grp_fu_466_ce = 1'b1;
    end else begin
        grp_fu_466_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem0_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        tile_a_ce0_local = 1'b1;
    end else begin
        tile_a_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign accumulator_2_out = accumulator_1_fu_100;

assign add_ln310_2_fu_385_p2 = (zext_ln310_7_cast_reg_528 + add_ln310_reg_547);

assign add_ln310_3_fu_392_p2 = (add_ln310_2_fu_385_p2 + zext_ln310_2_fu_389_p1);

assign add_ln310_4_fu_433_p2 = (zext_ln488_cast_reg_523 + add_ln492_1_reg_552);

assign add_ln310_5_fu_437_p2 = (add_ln310_4_fu_433_p2 + zext_ln304_fu_430_p1);

assign add_ln310_fu_339_p2 = (zext_ln310_fu_323_p1 + zext_ln310_1_fu_335_p1);

assign add_ln488_1_fu_269_p2 = (ic_fu_116 + 6'd1);

assign add_ln488_fu_214_p2 = (ap_sig_allocacmp_indvar_flatten14_load + 9'd1);

assign add_ln490_1_fu_351_p2 = (indvar_flatten_fu_112 + 4'd1);

assign add_ln490_fu_283_p2 = (select_ln486_fu_243_p3 + 2'd1);

assign add_ln492_1_fu_418_p2 = (p_shl_fu_398_p3 + zext_ln492_fu_414_p1);

assign add_ln492_fu_345_p2 = (kx_mid2_fu_295_p3 + 2'd1);

assign and_ln486_fu_263_p2 = (xor_ln486_fu_251_p2 & icmp_ln492_fu_257_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_149 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_289_p2 = (icmp_ln490_fu_237_p2 | and_ln486_fu_263_p2);

assign icmp_ln488_fu_208_p2 = ((ap_sig_allocacmp_indvar_flatten14_load == 9'd288) ? 1'b1 : 1'b0);

assign icmp_ln490_fu_237_p2 = ((indvar_flatten_fu_112 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln492_fu_257_p2 = ((kx_fu_104 == 2'd3) ? 1'b1 : 1'b0);

assign kx_mid2_fu_295_p3 = ((empty_fu_289_p2[0:0] == 1'b1) ? 2'd0 : kx_fu_104);

assign m_axi_gmem0_0_ARADDR = 64'd0;

assign m_axi_gmem0_0_ARBURST = 2'd0;

assign m_axi_gmem0_0_ARCACHE = 4'd0;

assign m_axi_gmem0_0_ARID = 1'd0;

assign m_axi_gmem0_0_ARLEN = 32'd0;

assign m_axi_gmem0_0_ARLOCK = 2'd0;

assign m_axi_gmem0_0_ARPROT = 3'd0;

assign m_axi_gmem0_0_ARQOS = 4'd0;

assign m_axi_gmem0_0_ARREGION = 4'd0;

assign m_axi_gmem0_0_ARSIZE = 3'd0;

assign m_axi_gmem0_0_ARUSER = 1'd0;

assign m_axi_gmem0_0_ARVALID = 1'b0;

assign m_axi_gmem0_0_AWADDR = 64'd0;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = 32'd0;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_AWVALID = 1'b0;

assign m_axi_gmem0_0_BREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = 8'd0;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 1'd0;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign m_axi_gmem0_0_WVALID = 1'b0;

assign p_shl_fu_398_p3 = {{add_ln310_3_fu_392_p2}, {5'd0}};

assign select_ln486_fu_243_p3 = ((icmp_ln490_fu_237_p2[0:0] == 1'b1) ? 2'd0 : ky_fu_108);

assign select_ln488_fu_275_p3 = ((icmp_ln490_fu_237_p2[0:0] == 1'b1) ? add_ln488_1_fu_269_p2 : ic_fu_116);

assign select_ln490_1_fu_357_p3 = ((icmp_ln490_fu_237_p2[0:0] == 1'b1) ? 4'd1 : add_ln490_1_fu_351_p2);

assign select_ln490_fu_303_p3 = ((and_ln486_fu_263_p2[0:0] == 1'b1) ? add_ln490_fu_283_p2 : select_ln486_fu_243_p3);

assign tile_a_address0 = zext_ln495_fu_443_p1;

assign tile_a_ce0 = tile_a_ce0_local;

assign tmp_2_fu_327_p3 = {{trunc_ln310_fu_311_p1}, {3'd0}};

assign tmp_3_fu_406_p3 = {{add_ln310_3_fu_392_p2}, {3'd0}};

assign tmp_fu_315_p3 = {{trunc_ln310_fu_311_p1}, {5'd0}};

assign trunc_ln310_fu_311_p1 = select_ln488_fu_275_p3[4:0];

assign xor_ln486_fu_251_p2 = (icmp_ln490_fu_237_p2 ^ 1'd1);

assign zext_ln304_fu_430_p1 = kx_mid2_reg_537_pp0_iter2_reg;

assign zext_ln310_1_fu_335_p1 = tmp_2_fu_327_p3;

assign zext_ln310_2_fu_389_p1 = select_ln490_reg_542;

assign zext_ln310_7_cast_fu_171_p1 = zext_ln310_7;

assign zext_ln310_fu_323_p1 = tmp_fu_315_p3;

assign zext_ln488_cast_fu_167_p1 = zext_ln488;

assign zext_ln492_fu_414_p1 = tmp_3_fu_406_p3;

assign zext_ln495_fu_443_p1 = add_ln310_5_fu_437_p2;

always @ (posedge ap_clk) begin
    zext_ln488_cast_reg_523[15:6] <= 10'b0000000000;
    zext_ln310_7_cast_reg_528[10:6] <= 5'b00000;
    add_ln310_reg_547[2:0] <= 3'b000;
    add_ln492_1_reg_552[2:0] <= 3'b000;
end

endmodule //restoration_top_residual_block_tiled_Pipeline_VITIS_LOOP_488_4_VITIS_LOOP_490_5_VITIS_LOOP_492_6
