// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module restoration_top_conv3x3_valid_11 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        output_r_q0,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        weights
);

parameter    ap_ST_fsm_pp0_stage0 = 53'd1;
parameter    ap_ST_fsm_pp0_stage1 = 53'd2;
parameter    ap_ST_fsm_pp0_stage2 = 53'd4;
parameter    ap_ST_fsm_pp0_stage3 = 53'd8;
parameter    ap_ST_fsm_pp0_stage4 = 53'd16;
parameter    ap_ST_fsm_pp0_stage5 = 53'd32;
parameter    ap_ST_fsm_pp0_stage6 = 53'd64;
parameter    ap_ST_fsm_pp0_stage7 = 53'd128;
parameter    ap_ST_fsm_pp0_stage8 = 53'd256;
parameter    ap_ST_fsm_pp0_stage9 = 53'd512;
parameter    ap_ST_fsm_pp0_stage10 = 53'd1024;
parameter    ap_ST_fsm_pp0_stage11 = 53'd2048;
parameter    ap_ST_fsm_pp0_stage12 = 53'd4096;
parameter    ap_ST_fsm_pp0_stage13 = 53'd8192;
parameter    ap_ST_fsm_pp0_stage14 = 53'd16384;
parameter    ap_ST_fsm_pp0_stage15 = 53'd32768;
parameter    ap_ST_fsm_pp0_stage16 = 53'd65536;
parameter    ap_ST_fsm_pp0_stage17 = 53'd131072;
parameter    ap_ST_fsm_pp0_stage18 = 53'd262144;
parameter    ap_ST_fsm_pp0_stage19 = 53'd524288;
parameter    ap_ST_fsm_pp0_stage20 = 53'd1048576;
parameter    ap_ST_fsm_pp0_stage21 = 53'd2097152;
parameter    ap_ST_fsm_pp0_stage22 = 53'd4194304;
parameter    ap_ST_fsm_pp0_stage23 = 53'd8388608;
parameter    ap_ST_fsm_pp0_stage24 = 53'd16777216;
parameter    ap_ST_fsm_pp0_stage25 = 53'd33554432;
parameter    ap_ST_fsm_pp0_stage26 = 53'd67108864;
parameter    ap_ST_fsm_pp0_stage27 = 53'd134217728;
parameter    ap_ST_fsm_pp0_stage28 = 53'd268435456;
parameter    ap_ST_fsm_pp0_stage29 = 53'd536870912;
parameter    ap_ST_fsm_pp0_stage30 = 53'd1073741824;
parameter    ap_ST_fsm_pp0_stage31 = 53'd2147483648;
parameter    ap_ST_fsm_pp0_stage32 = 53'd4294967296;
parameter    ap_ST_fsm_pp0_stage33 = 53'd8589934592;
parameter    ap_ST_fsm_pp0_stage34 = 53'd17179869184;
parameter    ap_ST_fsm_pp0_stage35 = 53'd34359738368;
parameter    ap_ST_fsm_pp0_stage36 = 53'd68719476736;
parameter    ap_ST_fsm_pp0_stage37 = 53'd137438953472;
parameter    ap_ST_fsm_pp0_stage38 = 53'd274877906944;
parameter    ap_ST_fsm_pp0_stage39 = 53'd549755813888;
parameter    ap_ST_fsm_pp0_stage40 = 53'd1099511627776;
parameter    ap_ST_fsm_pp0_stage41 = 53'd2199023255552;
parameter    ap_ST_fsm_pp0_stage42 = 53'd4398046511104;
parameter    ap_ST_fsm_pp0_stage43 = 53'd8796093022208;
parameter    ap_ST_fsm_pp0_stage44 = 53'd17592186044416;
parameter    ap_ST_fsm_pp0_stage45 = 53'd35184372088832;
parameter    ap_ST_fsm_pp0_stage46 = 53'd70368744177664;
parameter    ap_ST_fsm_pp0_stage47 = 53'd140737488355328;
parameter    ap_ST_fsm_pp0_stage48 = 53'd281474976710656;
parameter    ap_ST_fsm_pp0_stage49 = 53'd562949953421312;
parameter    ap_ST_fsm_pp0_stage50 = 53'd1125899906842624;
parameter    ap_ST_fsm_pp0_stage51 = 53'd2251799813685248;
parameter    ap_ST_fsm_pp0_stage52 = 53'd4503599627370496;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [16:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [7:0] output_r_d0;
input  [7:0] output_r_q0;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [7:0] m_axi_gmem0_0_WDATA;
output  [0:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [7:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [10:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [63:0] weights;

reg ap_idle;
reg m_axi_gmem0_0_ARVALID;
reg m_axi_gmem0_0_RREADY;

(* fsm_encoding = "none" *) reg   [52:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_pp0_stage9_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln368_reg_1805;
reg    ap_condition_exit_pp0_iter0_stage9;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage52;
wire    ap_block_pp0_stage52_subdone;
wire   [4:0] reduce_weight_scale_address0;
wire   [31:0] reduce_weight_scale_q0;
wire   [4:0] reduce_bias_address0;
wire   [31:0] reduce_bias_q0;
reg    gmem0_blk_n_AR;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_grp1;
reg   [0:0] first_iter_0_reg_1948;
reg   [0:0] first_iter_1_mid2_reg_1944;
reg   [0:0] first_iter_2_mid2_reg_1925;
reg    gmem0_blk_n_R;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_pp0_stage11_grp2;
wire   [31:0] grp_fu_476_p2;
reg   [31:0] reg_496;
wire    ap_CS_fsm_pp0_stage22;
wire    ap_block_pp0_stage22_11001;
wire    ap_CS_fsm_pp0_stage26;
wire    ap_block_pp0_stage26_11001;
wire   [31:0] grp_fu_472_p2;
reg   [31:0] reg_502;
wire    ap_CS_fsm_pp0_stage31;
wire    ap_block_pp0_stage31_11001;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_11001;
wire    ap_block_pp0_stage0_11001;
reg   [3:0] indvar_flatten_load_reg_1800;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [0:0] icmp_ln368_fu_582_p2;
wire   [0:0] icmp_ln370_fu_597_p2;
reg   [0:0] icmp_ln370_reg_1809;
wire   [0:0] xor_ln368_fu_603_p2;
reg   [0:0] xor_ln368_reg_1819;
wire   [0:0] and_ln368_3_fu_633_p2;
reg   [0:0] and_ln368_3_reg_1824;
wire   [0:0] not_exitcond_flatten42_mid2121130_fu_659_p2;
reg   [0:0] not_exitcond_flatten42_mid2121130_reg_1832;
wire   [0:0] exitcond_flatten_mid271_fu_665_p2;
reg   [0:0] exitcond_flatten_mid271_reg_1837;
wire   [0:0] exitcond_flatten16_mid275_fu_677_p2;
reg   [0:0] exitcond_flatten16_mid275_reg_1843;
wire   [0:0] empty_64_fu_683_p2;
reg   [0:0] empty_64_reg_1852;
wire   [0:0] not_exitcond_flatten16_mid275_fu_689_p2;
reg   [0:0] not_exitcond_flatten16_mid275_reg_1858;
wire   [15:0] add_ln392_2_fu_719_p2;
reg   [15:0] add_ln392_2_reg_1864;
wire   [4:0] trunc_ln310_fu_731_p1;
reg   [4:0] trunc_ln310_reg_1879;
reg   [4:0] trunc_ln310_reg_1879_pp0_iter1_reg;
wire   [10:0] add_ln376_1_fu_735_p2;
reg   [10:0] add_ln376_1_reg_1885;
wire   [11:0] add_ln372_1_fu_741_p2;
reg   [11:0] add_ln372_1_reg_1890;
wire   [0:0] empty_63_fu_834_p2;
reg   [0:0] empty_63_reg_1895;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire   [0:0] empty_65_fu_860_p2;
reg   [0:0] empty_65_reg_1900;
wire   [6:0] ic_mid221_fu_864_p3;
reg   [6:0] ic_mid221_reg_1905;
wire   [0:0] exitcond_flatten_mid239_fu_882_p2;
reg   [0:0] exitcond_flatten_mid239_reg_1910;
wire   [6:0] add_ln376_fu_886_p2;
reg   [6:0] add_ln376_reg_1915;
wire   [1:0] ky_mid26_fu_903_p3;
reg   [1:0] ky_mid26_reg_1920;
wire   [0:0] first_iter_2_mid2_fu_917_p3;
wire   [0:0] icmp_ln380_mid213_fu_946_p2;
reg   [0:0] icmp_ln380_mid213_reg_1929;
wire   [1:0] add_ln378_fu_952_p2;
reg   [1:0] add_ln378_reg_1934;
wire   [1:0] kx_mid2_fu_974_p3;
reg   [1:0] kx_mid2_reg_1939;
wire   [0:0] first_iter_1_mid2_fu_988_p3;
wire   [0:0] first_iter_0_fu_996_p2;
reg   [63:0] gmem0_addr_reg_1952;
reg   [31:0] reduce_weight_scale_load_reg_1958;
reg   [31:0] reduce_bias_load_reg_1963;
wire   [0:0] trunc_ln410_fu_1026_p1;
reg   [0:0] trunc_ln410_reg_1968;
reg   [0:0] trunc_ln410_reg_1968_pp0_iter1_reg;
wire   [0:0] icmp_ln380_1_fu_1036_p2;
reg   [0:0] icmp_ln380_1_reg_1975;
reg   [0:0] icmp_ln380_1_reg_1975_pp0_iter1_reg;
wire   [0:0] trunc_ln387_fu_1127_p1;
reg   [0:0] trunc_ln387_reg_1979;
wire    ap_block_pp0_stage9_11001;
reg   [15:0] tmp_24_reg_1985;
wire   [0:0] icmp_ln378_1_fu_1228_p2;
reg   [0:0] icmp_ln378_1_reg_1990;
wire   [0:0] icmp_ln376_1_fu_1234_p2;
reg   [0:0] icmp_ln376_1_reg_1994;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_pp0_stage10_11001;
reg  signed [7:0] pixel_reg_2003;
wire    ap_block_pp0_stage11_11001_grp0;
reg    ap_block_pp0_stage11_subdone_grp0_done_reg;
wire    ap_block_pp0_stage11_subdone_grp0;
reg    ap_block_pp0_stage11_subdone;
reg  signed [7:0] gmem0_addr_read_reg_2008;
reg    ap_block_state12_pp0_stage11_iter0_grp2;
reg    ap_block_pp0_stage11_11001_grp2;
wire   [31:0] accumulator_fu_1297_p2;
reg   [31:0] accumulator_reg_2013;
wire    ap_CS_fsm_pp0_stage12;
wire    ap_block_pp0_stage12_11001;
wire   [31:0] grp_fu_486_p1;
reg   [31:0] conv8_reg_2019;
wire    ap_CS_fsm_pp0_stage18;
wire    ap_block_pp0_stage18_11001;
wire   [31:0] grp_fu_481_p2;
reg   [31:0] q_reg_2024;
wire    ap_CS_fsm_pp0_stage47;
wire    ap_block_pp0_stage47_11001;
wire   [31:0] q_15_fu_1348_p3;
reg   [31:0] q_15_reg_2031;
wire    ap_CS_fsm_pp0_stage49;
wire    ap_block_pp0_stage49_11001;
wire   [31:0] q_16_fu_1396_p3;
reg   [31:0] q_16_reg_2038;
wire    ap_CS_fsm_pp0_stage51;
wire    ap_block_pp0_stage51_11001;
wire   [31:0] select_ln100_fu_1444_p3;
reg   [31:0] select_ln100_reg_2045;
reg   [0:0] xs_sign_reg_2050;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_11001;
wire   [22:0] trunc_ln342_fu_1472_p1;
reg   [22:0] trunc_ln342_reg_2055;
wire   [0:0] tmp_77_fu_1486_p3;
reg   [0:0] tmp_77_reg_2060;
wire   [8:0] select_ln18_fu_1504_p3;
reg   [8:0] select_ln18_reg_2065;
wire   [31:0] val_fu_1564_p3;
reg   [31:0] val_reg_2070;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_11001;
wire   [31:0] qi_9_fu_1598_p3;
reg   [31:0] qi_9_reg_2076;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_pp0_stage8_11001;
wire   [7:0] trunc_ln108_fu_1606_p1;
reg   [7:0] trunc_ln108_reg_2081;
wire   [63:0] zext_ln368_fu_725_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln383_fu_1270_p1;
wire    ap_block_pp0_stage10;
wire   [63:0] zext_ln409_fu_1706_p1;
wire    ap_block_pp0_stage9;
wire   [63:0] add_ln392_1_fu_1015_p2;
wire    ap_block_pp0_stage2;
reg    ap_predicate_op207_readreq_state4;
reg    ap_block_state4_io_grp1;
reg    ap_block_pp0_stage3_11001_grp1;
reg   [31:0] accumulator_3_fu_224;
wire    ap_CS_fsm_pp0_stage13;
wire    ap_block_pp0_stage13_11001;
wire    ap_loop_init;
wire    ap_block_pp0_stage12;
reg   [1:0] kx_fu_228;
wire   [1:0] add_ln380_fu_1030_p2;
reg   [1:0] ky_fu_232;
wire   [1:0] select_ln378_fu_1122_p3;
reg   [3:0] indvar_flatten_fu_236;
wire   [3:0] select_ln378_2_fu_1047_p3;
reg   [6:0] ic_fu_240;
wire   [6:0] select_ln376_fu_1117_p3;
reg   [10:0] indvar_flatten14_fu_244;
wire   [10:0] select_ln376_2_fu_1055_p3;
reg   [1:0] x_fu_248;
wire   [1:0] select_ln372_fu_1110_p3;
reg   [11:0] indvar_flatten40_fu_252;
wire   [11:0] select_ln372_1_fu_1062_p3;
reg   [1:0] y_fu_256;
wire   [1:0] select_ln370_fu_853_p3;
reg   [12:0] indvar_flatten76_fu_260;
wire   [12:0] select_ln370_1_fu_753_p3;
reg   [5:0] oc_fu_264;
wire   [5:0] select_ln368_3_fu_645_p3;
reg   [16:0] indvar_flatten122_fu_268;
wire   [16:0] add_ln368_1_fu_588_p2;
reg    reduce_weight_scale_ce0_local;
reg    reduce_bias_ce0_local;
reg    output_r_ce0_local;
reg   [16:0] output_r_address0_local;
reg    output_r_we0_local;
wire   [7:0] select_ln108_fu_1681_p3;
reg   [31:0] grp_fu_472_p0;
reg   [31:0] grp_fu_472_p1;
wire    ap_CS_fsm_pp0_stage27;
wire    ap_block_pp0_stage27;
reg   [31:0] grp_fu_476_p0;
reg   [31:0] grp_fu_476_p1;
wire    ap_CS_fsm_pp0_stage19;
wire    ap_block_pp0_stage19;
wire    ap_CS_fsm_pp0_stage23;
wire    ap_block_pp0_stage23;
wire    ap_CS_fsm_pp0_stage32;
wire    ap_block_pp0_stage32;
wire    ap_block_pp0_stage13;
reg   [31:0] grp_fu_489_p0;
reg   [31:0] grp_fu_489_p1;
wire    ap_CS_fsm_pp0_stage48;
wire    ap_block_pp0_stage48;
wire    ap_CS_fsm_pp0_stage50;
wire    ap_block_pp0_stage50;
wire    ap_block_pp0_stage52;
wire   [0:0] icmp_ln378_fu_609_p2;
wire   [0:0] icmp_ln372_fu_627_p2;
wire   [5:0] add_ln368_fu_639_p2;
wire   [0:0] exitcond_flatten42_not131_fu_653_p2;
wire   [0:0] and_ln368_1_fu_615_p2;
wire   [0:0] icmp_ln376_fu_621_p2;
wire   [0:0] and_ln368_2_fu_671_p2;
wire   [14:0] tmp_fu_695_p3;
wire   [11:0] tmp_69_fu_707_p3;
wire   [15:0] zext_ln392_2_fu_703_p1;
wire   [15:0] zext_ln392_3_fu_715_p1;
wire   [12:0] add_ln370_1_fu_747_p2;
wire   [0:0] first_iter_2179_fu_795_p2;
wire   [0:0] first_iter_1181_fu_806_p2;
wire   [0:0] icmp_ln380_fu_817_p2;
wire   [1:0] select_ln368_fu_788_p3;
wire   [0:0] or_ln368_fu_801_p2;
wire   [0:0] or_ln368_1_fu_812_p2;
wire   [0:0] and_ln368_fu_823_p2;
wire   [1:0] add_ln370_fu_828_p2;
wire   [0:0] first_iter_2_mid261_fu_838_p2;
wire   [0:0] first_iter_1_mid265_fu_843_p2;
wire   [0:0] empty_66_fu_892_p2;
wire   [0:0] empty_67_fu_897_p2;
wire   [0:0] first_iter_2_mid1_fu_911_p2;
wire   [0:0] first_iter_2_mid229_fu_872_p2;
wire   [0:0] first_iter_1_mid233_fu_877_p2;
wire   [0:0] exitcond_flatten_mid271_not_fu_931_p2;
wire   [0:0] icmp_ln380_mid267_fu_848_p2;
wire   [0:0] icmp_ln380_mid235_fu_941_p2;
wire   [0:0] not_exitcond_flatten_mid239_fu_936_p2;
wire   [0:0] empty_68_fu_958_p2;
wire   [0:0] empty_69_fu_963_p2;
wire   [0:0] empty_70_fu_969_p2;
wire   [0:0] first_iter_1_mid1_fu_982_p2;
wire   [0:0] first_iter_1_mid211_fu_925_p2;
wire   [18:0] zext_ln392_fu_1002_p1;
wire   [18:0] add_ln392_fu_1005_p2;
wire   [63:0] zext_ln392_1_fu_1011_p1;
wire   [3:0] add_ln378_1_fu_1042_p2;
wire   [1:0] x_mid247_fu_1097_p3;
wire   [1:0] add_ln372_fu_1104_p2;
wire   [5:0] trunc_ln310_3_fu_1131_p1;
wire   [10:0] tmp_73_fu_1135_p3;
wire   [8:0] tmp_74_fu_1147_p3;
wire   [11:0] zext_ln310_20_fu_1143_p1;
wire   [11:0] zext_ln310_21_fu_1155_p1;
wire   [11:0] add_ln310_28_fu_1159_p2;
wire   [10:0] tmp_23_fu_1169_p4;
wire   [11:0] tmp2_fu_1179_p3;
wire   [11:0] zext_ln310_12_fu_1165_p1;
wire   [11:0] add_ln310_17_fu_1186_p2;
wire   [14:0] tmp_75_fu_1200_p3;
wire   [16:0] p_shl11_fu_1192_p3;
wire   [16:0] zext_ln380_fu_1208_p1;
wire   [16:0] add_ln380_3_fu_1212_p2;
wire   [16:0] tmp3_fu_1258_p3;
wire   [16:0] zext_ln304_fu_1255_p1;
wire   [16:0] add_ln310_fu_1264_p2;
wire   [15:0] mul_ln396_fu_350_p2;
wire  signed [31:0] sext_ln395_fu_1293_p1;
wire   [31:0] accumulator_10_mid227_fu_1278_p3;
wire    ap_block_pp0_stage49;
wire   [31:0] bitcast_ln93_fu_1307_p1;
wire   [7:0] tmp_25_fu_1310_p4;
wire   [22:0] trunc_ln93_fu_1320_p1;
wire   [0:0] icmp_ln93_7_fu_1330_p2;
wire   [0:0] icmp_ln93_fu_1324_p2;
wire   [0:0] or_ln93_fu_1336_p2;
wire   [0:0] grp_fu_489_p2;
wire   [0:0] and_ln93_fu_1342_p2;
wire    ap_block_pp0_stage51;
wire   [31:0] bitcast_ln96_fu_1355_p1;
wire   [7:0] tmp_27_fu_1358_p4;
wire   [22:0] trunc_ln96_fu_1368_p1;
wire   [0:0] icmp_ln96_7_fu_1378_p2;
wire   [0:0] icmp_ln96_fu_1372_p2;
wire   [0:0] or_ln96_fu_1384_p2;
wire   [0:0] and_ln96_fu_1390_p2;
wire    ap_block_pp0_stage0;
wire   [31:0] bitcast_ln100_fu_1403_p1;
wire   [7:0] tmp_29_fu_1406_p4;
wire   [22:0] trunc_ln100_fu_1416_p1;
wire   [0:0] icmp_ln100_7_fu_1426_p2;
wire   [0:0] icmp_ln100_fu_1420_p2;
wire   [0:0] or_ln100_fu_1432_p2;
wire   [0:0] and_ln100_fu_1438_p2;
wire    ap_block_pp0_stage6;
wire   [31:0] data_fu_1452_p1;
wire   [7:0] xs_exp_fu_1464_p3;
wire   [8:0] zext_ln317_fu_1476_p1;
wire   [8:0] add_ln317_fu_1480_p2;
wire   [7:0] sub_ln18_fu_1494_p2;
wire  signed [8:0] sext_ln18_fu_1500_p1;
wire    ap_block_pp0_stage7;
wire   [24:0] mantissa_fu_1512_p4;
wire  signed [31:0] sext_ln18_9_fu_1525_p1;
wire   [78:0] zext_ln15_fu_1521_p1;
wire   [78:0] zext_ln18_fu_1528_p1;
wire   [78:0] lshr_ln18_fu_1532_p2;
wire   [78:0] shl_ln18_fu_1538_p2;
wire   [31:0] tmp_39_fu_1544_p4;
wire   [31:0] tmp_40_fu_1554_p4;
wire    ap_block_pp0_stage8;
wire   [31:0] result_16_fu_1571_p2;
wire   [31:0] result_fu_1576_p3;
wire   [24:0] tmp_78_fu_1582_p4;
wire   [0:0] icmp_ln102_fu_1592_p2;
wire   [9:0] tmp_70_fu_1610_p3;
wire   [7:0] tmp_71_fu_1621_p3;
wire   [10:0] zext_ln310_fu_1617_p1;
wire   [10:0] zext_ln310_19_fu_1628_p1;
wire   [10:0] add_ln310_27_fu_1632_p2;
wire   [9:0] tmp_s_fu_1638_p4;
wire   [13:0] tmp_72_fu_1657_p4;
wire   [15:0] p_shl_fu_1648_p4;
wire   [15:0] zext_ln372_fu_1666_p1;
wire   [0:0] icmp_ln105_fu_1676_p2;
wire   [15:0] add_ln372_4_fu_1670_p2;
wire   [14:0] tmp_31_fu_1689_p4;
wire   [15:0] add_ln310_s_fu_1699_p3;
reg    grp_fu_472_ce;
reg    ap_block_pp0_stage3_11001;
wire    ap_block_pp0_stage4_11001;
wire    ap_block_pp0_stage27_11001;
wire    ap_block_pp0_stage28_11001;
wire    ap_CS_fsm_pp0_stage28;
wire    ap_block_pp0_stage29_11001;
wire    ap_CS_fsm_pp0_stage29;
wire    ap_block_pp0_stage30_11001;
wire    ap_CS_fsm_pp0_stage30;
wire    ap_block_pp0_stage3_11001_grp0;
reg    ap_block_pp0_stage3_subdone_grp0_done_reg;
wire    ap_block_pp0_stage3_subdone_grp0;
reg    ap_block_pp0_stage3_subdone;
wire    ap_CS_fsm_pp0_stage4;
reg    grp_fu_476_ce;
wire    ap_block_pp0_stage19_11001;
wire    ap_block_pp0_stage20_11001;
wire    ap_CS_fsm_pp0_stage20;
wire    ap_block_pp0_stage21_11001;
wire    ap_CS_fsm_pp0_stage21;
wire    ap_block_pp0_stage23_11001;
wire    ap_block_pp0_stage24_11001;
wire    ap_CS_fsm_pp0_stage24;
wire    ap_block_pp0_stage25_11001;
wire    ap_CS_fsm_pp0_stage25;
reg    grp_fu_481_ce;
wire    ap_block_pp0_stage32_11001;
wire    ap_block_pp0_stage33_11001;
wire    ap_CS_fsm_pp0_stage33;
wire    ap_block_pp0_stage34_11001;
wire    ap_CS_fsm_pp0_stage34;
wire    ap_block_pp0_stage35_11001;
wire    ap_CS_fsm_pp0_stage35;
wire    ap_block_pp0_stage36_11001;
wire    ap_CS_fsm_pp0_stage36;
wire    ap_block_pp0_stage37_11001;
wire    ap_CS_fsm_pp0_stage37;
wire    ap_block_pp0_stage38_11001;
wire    ap_CS_fsm_pp0_stage38;
wire    ap_block_pp0_stage39_11001;
wire    ap_CS_fsm_pp0_stage39;
wire    ap_block_pp0_stage40_11001;
wire    ap_CS_fsm_pp0_stage40;
wire    ap_block_pp0_stage41_11001;
wire    ap_CS_fsm_pp0_stage41;
wire    ap_block_pp0_stage42_11001;
wire    ap_CS_fsm_pp0_stage42;
wire    ap_block_pp0_stage43_11001;
wire    ap_CS_fsm_pp0_stage43;
wire    ap_block_pp0_stage44_11001;
wire    ap_CS_fsm_pp0_stage44;
wire    ap_block_pp0_stage45_11001;
wire    ap_CS_fsm_pp0_stage45;
wire    ap_block_pp0_stage46_11001;
wire    ap_CS_fsm_pp0_stage46;
reg    grp_fu_486_ce;
wire    ap_block_pp0_stage14_11001;
wire    ap_CS_fsm_pp0_stage14;
wire    ap_block_pp0_stage15_11001;
wire    ap_CS_fsm_pp0_stage15;
wire    ap_block_pp0_stage16_11001;
wire    ap_CS_fsm_pp0_stage16;
wire    ap_block_pp0_stage17_11001;
wire    ap_CS_fsm_pp0_stage17;
reg    grp_fu_489_ce;
wire    ap_block_pp0_stage48_11001;
wire    ap_block_pp0_stage50_11001;
wire    ap_block_pp0_stage52_11001;
reg   [4:0] grp_fu_489_opcode;
wire    ap_block_pp0_stage48_00001;
wire    ap_block_pp0_stage50_00001;
wire    ap_block_pp0_stage52_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [52:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
wire    ap_block_pp0_stage10_subdone;
wire    ap_block_pp0_stage12_subdone;
wire    ap_block_pp0_stage13_subdone;
wire    ap_block_pp0_stage14_subdone;
wire    ap_block_pp0_stage15_subdone;
wire    ap_block_pp0_stage16_subdone;
wire    ap_block_pp0_stage17_subdone;
wire    ap_block_pp0_stage18_subdone;
wire    ap_block_pp0_stage19_subdone;
wire    ap_block_pp0_stage20_subdone;
wire    ap_block_pp0_stage21_subdone;
wire    ap_block_pp0_stage22_subdone;
wire    ap_block_pp0_stage23_subdone;
wire    ap_block_pp0_stage24_subdone;
wire    ap_block_pp0_stage25_subdone;
wire    ap_block_pp0_stage26_subdone;
wire    ap_block_pp0_stage27_subdone;
wire    ap_block_pp0_stage28_subdone;
wire    ap_block_pp0_stage29_subdone;
wire    ap_block_pp0_stage30_subdone;
wire    ap_block_pp0_stage31_subdone;
wire    ap_block_pp0_stage32_subdone;
wire    ap_block_pp0_stage33_subdone;
wire    ap_block_pp0_stage34_subdone;
wire    ap_block_pp0_stage35_subdone;
wire    ap_block_pp0_stage36_subdone;
wire    ap_block_pp0_stage37_subdone;
wire    ap_block_pp0_stage38_subdone;
wire    ap_block_pp0_stage39_subdone;
wire    ap_block_pp0_stage40_subdone;
wire    ap_block_pp0_stage41_subdone;
wire    ap_block_pp0_stage42_subdone;
wire    ap_block_pp0_stage43_subdone;
wire    ap_block_pp0_stage44_subdone;
wire    ap_block_pp0_stage45_subdone;
wire    ap_block_pp0_stage46_subdone;
wire    ap_block_pp0_stage47_subdone;
wire    ap_block_pp0_stage48_subdone;
wire    ap_block_pp0_stage49_subdone;
wire    ap_block_pp0_stage50_subdone;
wire    ap_block_pp0_stage51_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 53'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage11_subdone_grp0_done_reg = 1'b0;
#0 accumulator_3_fu_224 = 32'd0;
#0 kx_fu_228 = 2'd0;
#0 ky_fu_232 = 2'd0;
#0 indvar_flatten_fu_236 = 4'd0;
#0 ic_fu_240 = 7'd0;
#0 indvar_flatten14_fu_244 = 11'd0;
#0 x_fu_248 = 2'd0;
#0 indvar_flatten40_fu_252 = 12'd0;
#0 y_fu_256 = 2'd0;
#0 indvar_flatten76_fu_260 = 13'd0;
#0 oc_fu_264 = 6'd0;
#0 indvar_flatten122_fu_268 = 17'd0;
#0 ap_block_pp0_stage3_subdone_grp0_done_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

restoration_top_conv3x3_valid_11_reduce_weight_scale_ROM_1P_LUTRAM_1R #(
    .DataWidth( 32 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
reduce_weight_scale_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(reduce_weight_scale_address0),
    .ce0(reduce_weight_scale_ce0_local),
    .q0(reduce_weight_scale_q0)
);

restoration_top_conv3x3_valid_11_reduce_bias_ROM_1P_LUTRAM_1R #(
    .DataWidth( 32 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
reduce_bias_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(reduce_bias_address0),
    .ce0(reduce_bias_ce0_local),
    .q0(reduce_bias_q0)
);

restoration_top_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U173(
    .din0(gmem0_addr_read_reg_2008),
    .din1(pixel_reg_2003),
    .dout(mul_ln396_fu_350_p2)
);

restoration_top_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U174(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_472_p0),
    .din1(grp_fu_472_p1),
    .ce(grp_fu_472_ce),
    .dout(grp_fu_472_p2)
);

restoration_top_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U175(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_476_p0),
    .din1(grp_fu_476_p1),
    .ce(grp_fu_476_ce),
    .dout(grp_fu_476_p2)
);

restoration_top_fdiv_32ns_32ns_32_16_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_16_no_dsp_1_U176(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_502),
    .din1(32'd1023142020),
    .ce(grp_fu_481_ce),
    .dout(grp_fu_481_p2)
);

restoration_top_sitofp_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32ns_32_6_no_dsp_1_U177(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(accumulator_reg_2013),
    .ce(grp_fu_486_ce),
    .dout(grp_fu_486_p1)
);

restoration_top_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U178(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_489_p0),
    .din1(grp_fu_489_p1),
    .ce(grp_fu_489_ce),
    .opcode(grp_fu_489_opcode),
    .dout(grp_fu_489_p2)
);

restoration_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage9),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage11_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage11)) begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_block_pp0_stage11_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage11_subdone_grp0)) begin
                ap_block_pp0_stage11_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp0)) begin
                ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage9_subdone) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage9)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage9_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage52_subdone) & (1'b1 == ap_CS_fsm_pp0_stage52))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        accumulator_3_fu_224 <= 32'd0;
    end else if (((icmp_ln368_reg_1805 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13_11001) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        accumulator_3_fu_224 <= accumulator_reg_2013;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ic_fu_240 <= 7'd0;
    end else if (((icmp_ln368_reg_1805 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        ic_fu_240 <= select_ln376_fu_1117_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten122_fu_268 <= 17'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln368_fu_582_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        indvar_flatten122_fu_268 <= add_ln368_1_fu_588_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten14_fu_244 <= 11'd0;
    end else if (((icmp_ln368_reg_1805 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        indvar_flatten14_fu_244 <= select_ln376_2_fu_1055_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten40_fu_252 <= 12'd0;
    end else if (((icmp_ln368_reg_1805 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        indvar_flatten40_fu_252 <= select_ln372_1_fu_1062_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten76_fu_260 <= 13'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln368_fu_582_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        indvar_flatten76_fu_260 <= select_ln370_1_fu_753_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_fu_236 <= 4'd0;
    end else if (((icmp_ln368_reg_1805 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        indvar_flatten_fu_236 <= select_ln378_2_fu_1047_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kx_fu_228 <= 2'd0;
    end else if (((icmp_ln368_reg_1805 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        kx_fu_228 <= add_ln380_fu_1030_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ky_fu_232 <= 2'd0;
    end else if (((icmp_ln368_reg_1805 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        ky_fu_232 <= select_ln378_fu_1122_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        oc_fu_264 <= 6'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln368_fu_582_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        oc_fu_264 <= select_ln368_3_fu_645_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_fu_248 <= 2'd0;
    end else if (((icmp_ln368_reg_1805 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        x_fu_248 <= select_ln372_fu_1110_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y_fu_256 <= 2'd0;
    end else if (((icmp_ln368_reg_1805 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        y_fu_256 <= select_ln370_fu_853_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage12_11001) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        accumulator_reg_2013 <= accumulator_fu_1297_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln372_1_reg_1890 <= add_ln372_1_fu_741_p2;
        add_ln376_1_reg_1885 <= add_ln376_1_fu_735_p2;
        add_ln392_2_reg_1864[15 : 6] <= add_ln392_2_fu_719_p2[15 : 6];
        and_ln368_3_reg_1824 <= and_ln368_3_fu_633_p2;
        empty_64_reg_1852 <= empty_64_fu_683_p2;
        exitcond_flatten16_mid275_reg_1843 <= exitcond_flatten16_mid275_fu_677_p2;
        exitcond_flatten_mid271_reg_1837 <= exitcond_flatten_mid271_fu_665_p2;
        icmp_ln368_reg_1805 <= icmp_ln368_fu_582_p2;
        icmp_ln370_reg_1809 <= icmp_ln370_fu_597_p2;
        indvar_flatten_load_reg_1800 <= indvar_flatten_fu_236;
        not_exitcond_flatten16_mid275_reg_1858 <= not_exitcond_flatten16_mid275_fu_689_p2;
        not_exitcond_flatten42_mid2121130_reg_1832 <= not_exitcond_flatten42_mid2121130_fu_659_p2;
        trunc_ln310_reg_1879 <= trunc_ln310_fu_731_p1;
        trunc_ln310_reg_1879_pp0_iter1_reg <= trunc_ln310_reg_1879;
        xor_ln368_reg_1819 <= xor_ln368_fu_603_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln376_reg_1915 <= add_ln376_fu_886_p2;
        add_ln378_reg_1934 <= add_ln378_fu_952_p2;
        empty_63_reg_1895 <= empty_63_fu_834_p2;
        empty_65_reg_1900 <= empty_65_fu_860_p2;
        exitcond_flatten_mid239_reg_1910 <= exitcond_flatten_mid239_fu_882_p2;
        first_iter_0_reg_1948 <= first_iter_0_fu_996_p2;
        first_iter_1_mid2_reg_1944 <= first_iter_1_mid2_fu_988_p3;
        first_iter_2_mid2_reg_1925 <= first_iter_2_mid2_fu_917_p3;
        gmem0_addr_reg_1952 <= add_ln392_1_fu_1015_p2;
        ic_mid221_reg_1905 <= ic_mid221_fu_864_p3;
        icmp_ln380_1_reg_1975 <= icmp_ln380_1_fu_1036_p2;
        icmp_ln380_1_reg_1975_pp0_iter1_reg <= icmp_ln380_1_reg_1975;
        icmp_ln380_mid213_reg_1929 <= icmp_ln380_mid213_fu_946_p2;
        kx_mid2_reg_1939 <= kx_mid2_fu_974_p3;
        ky_mid26_reg_1920 <= ky_mid26_fu_903_p3;
        reduce_bias_load_reg_1963 <= reduce_bias_q0;
        reduce_weight_scale_load_reg_1958 <= reduce_weight_scale_q0;
        trunc_ln410_reg_1968 <= trunc_ln410_fu_1026_p1;
        trunc_ln410_reg_1968_pp0_iter1_reg <= trunc_ln410_reg_1968;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage18_11001) & (1'b1 == ap_CS_fsm_pp0_stage18))) begin
        conv8_reg_2019 <= grp_fu_486_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage11_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        gmem0_addr_read_reg_2008 <= m_axi_gmem0_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        icmp_ln376_1_reg_1994 <= icmp_ln376_1_fu_1234_p2;
        icmp_ln378_1_reg_1990 <= icmp_ln378_1_fu_1228_p2;
        tmp_24_reg_1985 <= {{add_ln380_3_fu_1212_p2[16:1]}};
        trunc_ln387_reg_1979 <= trunc_ln387_fu_1127_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage11_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        pixel_reg_2003 <= output_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage49_11001) & (1'b1 == ap_CS_fsm_pp0_stage49))) begin
        q_15_reg_2031 <= q_15_fu_1348_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage51_11001) & (1'b1 == ap_CS_fsm_pp0_stage51))) begin
        q_16_reg_2038 <= q_16_fu_1396_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage47_11001) & (1'b1 == ap_CS_fsm_pp0_stage47))) begin
        q_reg_2024 <= grp_fu_481_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        qi_9_reg_2076 <= qi_9_fu_1598_p3;
        trunc_ln108_reg_2081 <= trunc_ln108_fu_1606_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage26_11001) & (1'b1 == ap_CS_fsm_pp0_stage26)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage22_11001) & (1'b1 == ap_CS_fsm_pp0_stage22)))) begin
        reg_496 <= grp_fu_476_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage31_11001) & (1'b1 == ap_CS_fsm_pp0_stage31)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        reg_502 <= grp_fu_472_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln100_reg_2045[31] <= select_ln100_fu_1444_p3[31];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        select_ln18_reg_2065 <= select_ln18_fu_1504_p3;
        tmp_77_reg_2060 <= add_ln317_fu_1480_p2[32'd8];
        trunc_ln342_reg_2055 <= trunc_ln342_fu_1472_p1;
        xs_sign_reg_2050 <= data_fu_1452_p1[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        val_reg_2070 <= val_fu_1564_p3;
    end
end

always @ (*) begin
    if (((icmp_ln368_reg_1805 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_subdone) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        ap_condition_exit_pp0_iter0_stage9 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage9 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage9_subdone) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage52_subdone) & (1'b1 == ap_CS_fsm_pp0_stage52))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln368_reg_1805 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_grp1) & (first_iter_2_mid2_reg_1925 == 1'd1) & (first_iter_1_mid2_reg_1944 == 1'd1) & (first_iter_0_reg_1948 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        gmem0_blk_n_AR = m_axi_gmem0_0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln368_reg_1805 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_grp2) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        gmem0_blk_n_R = m_axi_gmem0_0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage31_11001) & (1'b1 == ap_CS_fsm_pp0_stage31)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage30_11001) & (1'b1 == ap_CS_fsm_pp0_stage30)) | ((1'b0 == ap_block_pp0_stage29_11001) & (1'b1 == ap_CS_fsm_pp0_stage29)) | ((1'b0 == ap_block_pp0_stage28_11001) & (1'b1 == ap_CS_fsm_pp0_stage28)) | ((1'b0 == ap_block_pp0_stage27_11001) & (1'b1 == ap_CS_fsm_pp0_stage27)))) begin
        grp_fu_472_ce = 1'b1;
    end else begin
        grp_fu_472_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_472_p0 = q_16_reg_2038;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage27) & (1'b1 == ap_CS_fsm_pp0_stage27))) begin
        grp_fu_472_p0 = reg_496;
    end else begin
        grp_fu_472_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_472_p1 = select_ln100_reg_2045;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage27) & (1'b1 == ap_CS_fsm_pp0_stage27))) begin
        grp_fu_472_p1 = reduce_bias_load_reg_1963;
    end else begin
        grp_fu_472_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage26_11001) & (1'b1 == ap_CS_fsm_pp0_stage26)) | ((1'b0 == ap_block_pp0_stage22_11001) & (1'b1 == ap_CS_fsm_pp0_stage22)) | ((1'b0 == ap_block_pp0_stage25_11001) & (1'b1 == ap_CS_fsm_pp0_stage25)) | ((1'b0 == ap_block_pp0_stage24_11001) & (1'b1 == ap_CS_fsm_pp0_stage24)) | ((1'b0 == ap_block_pp0_stage23_11001) & (1'b1 == ap_CS_fsm_pp0_stage23)) | ((1'b0 == ap_block_pp0_stage21_11001) & (1'b1 == ap_CS_fsm_pp0_stage21)) | ((1'b0 == ap_block_pp0_stage20_11001) & (1'b1 == ap_CS_fsm_pp0_stage20)) | ((1'b0 == ap_block_pp0_stage19_11001) & (1'b1 == ap_CS_fsm_pp0_stage19)))) begin
        grp_fu_476_ce = 1'b1;
    end else begin
        grp_fu_476_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage23) & (1'b1 == ap_CS_fsm_pp0_stage23))) begin
            grp_fu_476_p0 = reg_496;
        end else if (((1'b0 == ap_block_pp0_stage19) & (1'b1 == ap_CS_fsm_pp0_stage19))) begin
            grp_fu_476_p0 = conv8_reg_2019;
        end else begin
            grp_fu_476_p0 = 'bx;
        end
    end else begin
        grp_fu_476_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage23) & (1'b1 == ap_CS_fsm_pp0_stage23))) begin
            grp_fu_476_p1 = reduce_weight_scale_load_reg_1958;
        end else if (((1'b0 == ap_block_pp0_stage19) & (1'b1 == ap_CS_fsm_pp0_stage19))) begin
            grp_fu_476_p1 = 32'd1016786026;
        end else begin
            grp_fu_476_p1 = 'bx;
        end
    end else begin
        grp_fu_476_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage47_11001) & (1'b1 == ap_CS_fsm_pp0_stage47)) | ((1'b0 == ap_block_pp0_stage46_11001) & (1'b1 == ap_CS_fsm_pp0_stage46)) | ((1'b0 == ap_block_pp0_stage45_11001) & (1'b1 == ap_CS_fsm_pp0_stage45)) | ((1'b0 == ap_block_pp0_stage44_11001) & (1'b1 == ap_CS_fsm_pp0_stage44)) | ((1'b0 == ap_block_pp0_stage43_11001) & (1'b1 == ap_CS_fsm_pp0_stage43)) | ((1'b0 == ap_block_pp0_stage42_11001) & (1'b1 == ap_CS_fsm_pp0_stage42)) | ((1'b0 == ap_block_pp0_stage41_11001) & (1'b1 == ap_CS_fsm_pp0_stage41)) | ((1'b0 == ap_block_pp0_stage40_11001) & (1'b1 == ap_CS_fsm_pp0_stage40)) | ((1'b0 == ap_block_pp0_stage39_11001) & (1'b1 == ap_CS_fsm_pp0_stage39)) | ((1'b0 == ap_block_pp0_stage38_11001) & (1'b1 == ap_CS_fsm_pp0_stage38)) | ((1'b0 == ap_block_pp0_stage37_11001) & (1'b1 == ap_CS_fsm_pp0_stage37)) | ((1'b0 == ap_block_pp0_stage36_11001) & (1'b1 == ap_CS_fsm_pp0_stage36)) | ((1'b0 == ap_block_pp0_stage35_11001) & (1'b1 == ap_CS_fsm_pp0_stage35)) | ((1'b0 == ap_block_pp0_stage34_11001) & (1'b1 == 
    ap_CS_fsm_pp0_stage34)) | ((1'b0 == ap_block_pp0_stage33_11001) & (1'b1 == ap_CS_fsm_pp0_stage33)) | ((1'b0 == ap_block_pp0_stage32_11001) & (1'b1 == ap_CS_fsm_pp0_stage32)))) begin
        grp_fu_481_ce = 1'b1;
    end else begin
        grp_fu_481_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage13_11001) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((1'b0 == ap_block_pp0_stage18_11001) & (1'b1 == ap_CS_fsm_pp0_stage18)) | ((1'b0 == ap_block_pp0_stage17_11001) & (1'b1 == ap_CS_fsm_pp0_stage17)) | ((1'b0 == ap_block_pp0_stage16_11001) & (1'b1 == ap_CS_fsm_pp0_stage16)) | ((1'b0 == ap_block_pp0_stage15_11001) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((1'b0 == ap_block_pp0_stage14_11001) & (1'b1 == ap_CS_fsm_pp0_stage14)))) begin
        grp_fu_486_ce = 1'b1;
    end else begin
        grp_fu_486_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage51_11001) & (1'b1 == ap_CS_fsm_pp0_stage51)) | ((1'b0 == ap_block_pp0_stage49_11001) & (1'b1 == ap_CS_fsm_pp0_stage49)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage52_11001) & (1'b1 == ap_CS_fsm_pp0_stage52)) | ((1'b0 == ap_block_pp0_stage50_11001) & (1'b1 == ap_CS_fsm_pp0_stage50)) | ((1'b0 == ap_block_pp0_stage48_11001) & (1'b1 == ap_CS_fsm_pp0_stage48)))) begin
        grp_fu_489_ce = 1'b1;
    end else begin
        grp_fu_489_ce = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln368_reg_1805 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        if (((1'b0 == ap_block_pp0_stage52_00001) & (1'b1 == ap_CS_fsm_pp0_stage52))) begin
            grp_fu_489_opcode = 5'd3;
        end else if (((1'b0 == ap_block_pp0_stage50_00001) & (1'b1 == ap_CS_fsm_pp0_stage50))) begin
            grp_fu_489_opcode = 5'd4;
        end else if (((1'b0 == ap_block_pp0_stage48_00001) & (1'b1 == ap_CS_fsm_pp0_stage48))) begin
            grp_fu_489_opcode = 5'd2;
        end else begin
            grp_fu_489_opcode = 'bx;
        end
    end else begin
        grp_fu_489_opcode = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage52) & (1'b1 == ap_CS_fsm_pp0_stage52))) begin
            grp_fu_489_p0 = q_16_reg_2038;
        end else if (((1'b0 == ap_block_pp0_stage50) & (1'b1 == ap_CS_fsm_pp0_stage50))) begin
            grp_fu_489_p0 = q_15_reg_2031;
        end else if (((1'b0 == ap_block_pp0_stage48) & (1'b1 == ap_CS_fsm_pp0_stage48))) begin
            grp_fu_489_p0 = q_reg_2024;
        end else begin
            grp_fu_489_p0 = 'bx;
        end
    end else begin
        grp_fu_489_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage52) & (1'b1 == ap_CS_fsm_pp0_stage52))) begin
            grp_fu_489_p1 = 32'd0;
        end else if (((1'b0 == ap_block_pp0_stage50) & (1'b1 == ap_CS_fsm_pp0_stage50))) begin
            grp_fu_489_p1 = 32'd3271426048;
        end else if (((1'b0 == ap_block_pp0_stage48) & (1'b1 == ap_CS_fsm_pp0_stage48))) begin
            grp_fu_489_p1 = 32'd1123942400;
        end else begin
            grp_fu_489_p1 = 'bx;
        end
    end else begin
        grp_fu_489_p1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp1) & (ap_predicate_op207_readreq_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        m_axi_gmem0_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem0_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln368_reg_1805 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        m_axi_gmem0_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        output_r_address0_local = zext_ln409_fu_1706_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        output_r_address0_local = zext_ln383_fu_1270_p1;
    end else begin
        output_r_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)))) begin
        output_r_ce0_local = 1'b1;
    end else begin
        output_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln376_1_reg_1994 == 1'd1) & (icmp_ln378_1_reg_1990 == 1'd1) & (icmp_ln380_1_reg_1975_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        output_r_we0_local = 1'b1;
    end else begin
        output_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        reduce_bias_ce0_local = 1'b1;
    end else begin
        reduce_bias_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        reduce_weight_scale_ce0_local = 1'b1;
    end else begin
        reduce_weight_scale_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage9)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        ap_ST_fsm_pp0_stage13 : begin
            if ((1'b0 == ap_block_pp0_stage13_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end
        end
        ap_ST_fsm_pp0_stage14 : begin
            if ((1'b0 == ap_block_pp0_stage14_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end
        end
        ap_ST_fsm_pp0_stage15 : begin
            if ((1'b0 == ap_block_pp0_stage15_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end
        end
        ap_ST_fsm_pp0_stage16 : begin
            if ((1'b0 == ap_block_pp0_stage16_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage16;
            end
        end
        ap_ST_fsm_pp0_stage17 : begin
            if ((1'b0 == ap_block_pp0_stage17_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage17;
            end
        end
        ap_ST_fsm_pp0_stage18 : begin
            if ((1'b0 == ap_block_pp0_stage18_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage18;
            end
        end
        ap_ST_fsm_pp0_stage19 : begin
            if ((1'b0 == ap_block_pp0_stage19_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage19;
            end
        end
        ap_ST_fsm_pp0_stage20 : begin
            if ((1'b0 == ap_block_pp0_stage20_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage20;
            end
        end
        ap_ST_fsm_pp0_stage21 : begin
            if ((1'b0 == ap_block_pp0_stage21_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage21;
            end
        end
        ap_ST_fsm_pp0_stage22 : begin
            if ((1'b0 == ap_block_pp0_stage22_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage22;
            end
        end
        ap_ST_fsm_pp0_stage23 : begin
            if ((1'b0 == ap_block_pp0_stage23_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage23;
            end
        end
        ap_ST_fsm_pp0_stage24 : begin
            if ((1'b0 == ap_block_pp0_stage24_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage24;
            end
        end
        ap_ST_fsm_pp0_stage25 : begin
            if ((1'b0 == ap_block_pp0_stage25_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage25;
            end
        end
        ap_ST_fsm_pp0_stage26 : begin
            if ((1'b0 == ap_block_pp0_stage26_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage26;
            end
        end
        ap_ST_fsm_pp0_stage27 : begin
            if ((1'b0 == ap_block_pp0_stage27_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage27;
            end
        end
        ap_ST_fsm_pp0_stage28 : begin
            if ((1'b0 == ap_block_pp0_stage28_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage28;
            end
        end
        ap_ST_fsm_pp0_stage29 : begin
            if ((1'b0 == ap_block_pp0_stage29_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage29;
            end
        end
        ap_ST_fsm_pp0_stage30 : begin
            if ((1'b0 == ap_block_pp0_stage30_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage30;
            end
        end
        ap_ST_fsm_pp0_stage31 : begin
            if ((1'b0 == ap_block_pp0_stage31_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage31;
            end
        end
        ap_ST_fsm_pp0_stage32 : begin
            if ((1'b0 == ap_block_pp0_stage32_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage32;
            end
        end
        ap_ST_fsm_pp0_stage33 : begin
            if ((1'b0 == ap_block_pp0_stage33_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage34;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage33;
            end
        end
        ap_ST_fsm_pp0_stage34 : begin
            if ((1'b0 == ap_block_pp0_stage34_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage35;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage34;
            end
        end
        ap_ST_fsm_pp0_stage35 : begin
            if ((1'b0 == ap_block_pp0_stage35_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage36;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage35;
            end
        end
        ap_ST_fsm_pp0_stage36 : begin
            if ((1'b0 == ap_block_pp0_stage36_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage37;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage36;
            end
        end
        ap_ST_fsm_pp0_stage37 : begin
            if ((1'b0 == ap_block_pp0_stage37_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage37;
            end
        end
        ap_ST_fsm_pp0_stage38 : begin
            if ((1'b0 == ap_block_pp0_stage38_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage39;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage38;
            end
        end
        ap_ST_fsm_pp0_stage39 : begin
            if ((1'b0 == ap_block_pp0_stage39_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage40;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage39;
            end
        end
        ap_ST_fsm_pp0_stage40 : begin
            if ((1'b0 == ap_block_pp0_stage40_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage41;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage40;
            end
        end
        ap_ST_fsm_pp0_stage41 : begin
            if ((1'b0 == ap_block_pp0_stage41_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage42;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage41;
            end
        end
        ap_ST_fsm_pp0_stage42 : begin
            if ((1'b0 == ap_block_pp0_stage42_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage43;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage42;
            end
        end
        ap_ST_fsm_pp0_stage43 : begin
            if ((1'b0 == ap_block_pp0_stage43_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage44;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage43;
            end
        end
        ap_ST_fsm_pp0_stage44 : begin
            if ((1'b0 == ap_block_pp0_stage44_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage45;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage44;
            end
        end
        ap_ST_fsm_pp0_stage45 : begin
            if ((1'b0 == ap_block_pp0_stage45_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage46;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage45;
            end
        end
        ap_ST_fsm_pp0_stage46 : begin
            if ((1'b0 == ap_block_pp0_stage46_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage47;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage46;
            end
        end
        ap_ST_fsm_pp0_stage47 : begin
            if ((1'b0 == ap_block_pp0_stage47_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage48;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage47;
            end
        end
        ap_ST_fsm_pp0_stage48 : begin
            if ((1'b0 == ap_block_pp0_stage48_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage49;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage48;
            end
        end
        ap_ST_fsm_pp0_stage49 : begin
            if ((1'b0 == ap_block_pp0_stage49_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage50;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage49;
            end
        end
        ap_ST_fsm_pp0_stage50 : begin
            if ((1'b0 == ap_block_pp0_stage50_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage51;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage50;
            end
        end
        ap_ST_fsm_pp0_stage51 : begin
            if ((1'b0 == ap_block_pp0_stage51_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage52;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage51;
            end
        end
        ap_ST_fsm_pp0_stage52 : begin
            if ((1'b0 == ap_block_pp0_stage52_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage52;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign accumulator_10_mid227_fu_1278_p3 = ((empty_65_reg_1900[0:0] == 1'b1) ? 32'd0 : accumulator_3_fu_224);

assign accumulator_fu_1297_p2 = ($signed(sext_ln395_fu_1293_p1) + $signed(accumulator_10_mid227_fu_1278_p3));

assign add_ln310_17_fu_1186_p2 = (tmp2_fu_1179_p3 + zext_ln310_12_fu_1165_p1);

assign add_ln310_27_fu_1632_p2 = (zext_ln310_fu_1617_p1 + zext_ln310_19_fu_1628_p1);

assign add_ln310_28_fu_1159_p2 = (zext_ln310_20_fu_1143_p1 + zext_ln310_21_fu_1155_p1);

assign add_ln310_fu_1264_p2 = (tmp3_fu_1258_p3 + zext_ln304_fu_1255_p1);

assign add_ln310_s_fu_1699_p3 = {{tmp_31_fu_1689_p4}, {trunc_ln387_reg_1979}};

assign add_ln317_fu_1480_p2 = ($signed(zext_ln317_fu_1476_p1) + $signed(9'd385));

assign add_ln368_1_fu_588_p2 = (indvar_flatten122_fu_268 + 17'd1);

assign add_ln368_fu_639_p2 = (oc_fu_264 + 6'd1);

assign add_ln370_1_fu_747_p2 = (indvar_flatten76_fu_260 + 13'd1);

assign add_ln370_fu_828_p2 = (select_ln368_fu_788_p3 + 2'd1);

assign add_ln372_1_fu_741_p2 = (indvar_flatten40_fu_252 + 12'd1);

assign add_ln372_4_fu_1670_p2 = (p_shl_fu_1648_p4 + zext_ln372_fu_1666_p1);

assign add_ln372_fu_1104_p2 = (x_mid247_fu_1097_p3 + 2'd1);

assign add_ln376_1_fu_735_p2 = (indvar_flatten14_fu_244 + 11'd1);

assign add_ln376_fu_886_p2 = (ic_mid221_fu_864_p3 + 7'd1);

assign add_ln378_1_fu_1042_p2 = (indvar_flatten_load_reg_1800 + 4'd1);

assign add_ln378_fu_952_p2 = (ky_mid26_fu_903_p3 + 2'd1);

assign add_ln380_3_fu_1212_p2 = (p_shl11_fu_1192_p3 + zext_ln380_fu_1208_p1);

assign add_ln380_fu_1030_p2 = (kx_mid2_fu_974_p3 + 2'd1);

assign add_ln392_1_fu_1015_p2 = (zext_ln392_1_fu_1011_p1 + weights);

assign add_ln392_2_fu_719_p2 = (zext_ln392_2_fu_703_p1 + zext_ln392_3_fu_715_p1);

assign add_ln392_fu_1005_p2 = ($signed(zext_ln392_fu_1002_p1) + $signed(19'd387360));

assign and_ln100_fu_1438_p2 = (or_ln100_fu_1432_p2 & grp_fu_489_p2);

assign and_ln368_1_fu_615_p2 = (xor_ln368_fu_603_p2 & icmp_ln378_fu_609_p2);

assign and_ln368_2_fu_671_p2 = (xor_ln368_fu_603_p2 & icmp_ln376_fu_621_p2);

assign and_ln368_3_fu_633_p2 = (xor_ln368_fu_603_p2 & icmp_ln372_fu_627_p2);

assign and_ln368_fu_823_p2 = (xor_ln368_reg_1819 & icmp_ln380_fu_817_p2);

assign and_ln93_fu_1342_p2 = (or_ln93_fu_1336_p2 & grp_fu_489_p2);

assign and_ln96_fu_1390_p2 = (or_ln96_fu_1384_p2 & grp_fu_489_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage12 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage13 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp0_stage14 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_pp0_stage15 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_pp0_stage16 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_pp0_stage17 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_pp0_stage18 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_pp0_stage19 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage20 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_pp0_stage21 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_pp0_stage22 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_pp0_stage23 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_pp0_stage24 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_pp0_stage25 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_pp0_stage26 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_pp0_stage27 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_pp0_stage28 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_pp0_stage29 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage30 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_pp0_stage31 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_pp0_stage32 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_pp0_stage33 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_pp0_stage34 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_pp0_stage35 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_pp0_stage36 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_pp0_stage37 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_pp0_stage38 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_pp0_stage39 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage40 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_pp0_stage41 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_pp0_stage42 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_pp0_stage43 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_pp0_stage44 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_pp0_stage45 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_pp0_stage46 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_pp0_stage47 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_pp0_stage48 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_pp0_stage49 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage50 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_pp0_stage51 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_pp0_stage52 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage11_11001_grp2 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state12_pp0_stage11_iter0_grp2));
end

assign ap_block_pp0_stage11_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage11_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state12_pp0_stage11_iter0_grp2));
end

assign ap_block_pp0_stage11_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage16_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage16_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage17_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage17_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage18_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage18_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage19 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage19_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage19_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage20_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage20_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage21_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage21_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage22_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage22_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage23 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage23_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage23_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage24_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage24_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage25_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage25_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage26_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage26_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage27 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage27_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage27_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage28_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage28_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage29_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage29_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage30_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage30_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage31_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage31_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage32 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage32_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage32_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage33_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage33_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage34_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage34_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage35_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage35_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage36_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage36_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage37_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage37_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage38_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage38_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage39_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage39_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_io_grp1));
end

assign ap_block_pp0_stage3_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_io_grp1));
end

assign ap_block_pp0_stage3_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_io_grp1));
end

assign ap_block_pp0_stage3_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage40_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage40_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage41_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage41_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage42_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage42_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage43_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage43_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage44_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage44_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage45_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage45_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage46_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage46_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage47_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage47_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage48 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage48_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage48_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage48_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage49 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage49_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage49_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage50 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage50_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage50_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage50_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage51 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage51_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage51_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage52 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage52_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage52_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage52_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_pp0_stage11_iter0_grp2 = ((icmp_ln368_reg_1805 == 1'd0) & (m_axi_gmem0_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state4_io_grp1 = ((ap_predicate_op207_readreq_state4 == 1'b1) & (m_axi_gmem0_0_ARREADY == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage9;

always @ (*) begin
    ap_predicate_op207_readreq_state4 = ((icmp_ln368_reg_1805 == 1'd0) & (first_iter_2_mid2_reg_1925 == 1'd1) & (first_iter_1_mid2_reg_1944 == 1'd1) & (first_iter_0_reg_1948 == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign bitcast_ln100_fu_1403_p1 = q_16_reg_2038;

assign bitcast_ln93_fu_1307_p1 = q_reg_2024;

assign bitcast_ln96_fu_1355_p1 = q_15_reg_2031;

assign data_fu_1452_p1 = reg_502;

assign empty_63_fu_834_p2 = (icmp_ln370_reg_1809 | and_ln368_3_reg_1824);

assign empty_64_fu_683_p2 = (exitcond_flatten16_mid275_fu_677_p2 | and_ln368_3_fu_633_p2);

assign empty_65_fu_860_p2 = (icmp_ln370_reg_1809 | empty_64_reg_1852);

assign empty_66_fu_892_p2 = (exitcond_flatten_mid239_fu_882_p2 | exitcond_flatten16_mid275_reg_1843);

assign empty_67_fu_897_p2 = (empty_66_fu_892_p2 | empty_63_fu_834_p2);

assign empty_68_fu_958_p2 = (exitcond_flatten_mid239_fu_882_p2 | empty_64_reg_1852);

assign empty_69_fu_963_p2 = (icmp_ln380_mid213_fu_946_p2 | empty_68_fu_958_p2);

assign empty_70_fu_969_p2 = (icmp_ln370_reg_1809 | empty_69_fu_963_p2);

assign exitcond_flatten16_mid275_fu_677_p2 = (not_exitcond_flatten42_mid2121130_fu_659_p2 & and_ln368_2_fu_671_p2);

assign exitcond_flatten42_not131_fu_653_p2 = (icmp_ln372_fu_627_p2 ^ 1'd1);

assign exitcond_flatten_mid239_fu_882_p2 = (not_exitcond_flatten16_mid275_reg_1858 & exitcond_flatten_mid271_reg_1837);

assign exitcond_flatten_mid271_fu_665_p2 = (not_exitcond_flatten42_mid2121130_fu_659_p2 & and_ln368_1_fu_615_p2);

assign exitcond_flatten_mid271_not_fu_931_p2 = (exitcond_flatten_mid271_reg_1837 ^ 1'd1);

assign first_iter_0_fu_996_p2 = ((kx_mid2_fu_974_p3 == 2'd0) ? 1'b1 : 1'b0);

assign first_iter_1181_fu_806_p2 = ((ky_fu_232 == 2'd0) ? 1'b1 : 1'b0);

assign first_iter_1_mid1_fu_982_p2 = ((add_ln378_fu_952_p2 == 2'd0) ? 1'b1 : 1'b0);

assign first_iter_1_mid211_fu_925_p2 = (first_iter_1_mid233_fu_877_p2 | exitcond_flatten_mid239_fu_882_p2);

assign first_iter_1_mid233_fu_877_p2 = (first_iter_1_mid265_fu_843_p2 | exitcond_flatten16_mid275_reg_1843);

assign first_iter_1_mid265_fu_843_p2 = (or_ln368_1_fu_812_p2 | and_ln368_3_reg_1824);

assign first_iter_1_mid2_fu_988_p3 = ((icmp_ln380_mid213_fu_946_p2[0:0] == 1'b1) ? first_iter_1_mid1_fu_982_p2 : first_iter_1_mid211_fu_925_p2);

assign first_iter_2179_fu_795_p2 = ((ic_fu_240 == 7'd0) ? 1'b1 : 1'b0);

assign first_iter_2_mid1_fu_911_p2 = ((add_ln376_fu_886_p2 == 7'd0) ? 1'b1 : 1'b0);

assign first_iter_2_mid229_fu_872_p2 = (first_iter_2_mid261_fu_838_p2 | exitcond_flatten16_mid275_reg_1843);

assign first_iter_2_mid261_fu_838_p2 = (or_ln368_fu_801_p2 | and_ln368_3_reg_1824);

assign first_iter_2_mid2_fu_917_p3 = ((exitcond_flatten_mid239_fu_882_p2[0:0] == 1'b1) ? first_iter_2_mid1_fu_911_p2 : first_iter_2_mid229_fu_872_p2);

assign ic_mid221_fu_864_p3 = ((empty_65_fu_860_p2[0:0] == 1'b1) ? 7'd0 : ic_fu_240);

assign icmp_ln100_7_fu_1426_p2 = ((trunc_ln100_fu_1416_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln100_fu_1420_p2 = ((tmp_29_fu_1406_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln102_fu_1592_p2 = (($signed(tmp_78_fu_1582_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln105_fu_1676_p2 = (($signed(qi_9_reg_2076) < $signed(32'd4294967169)) ? 1'b1 : 1'b0);

assign icmp_ln368_fu_582_p2 = ((indvar_flatten122_fu_268 == 17'd73728) ? 1'b1 : 1'b0);

assign icmp_ln370_fu_597_p2 = ((indvar_flatten76_fu_260 == 13'd2304) ? 1'b1 : 1'b0);

assign icmp_ln372_fu_627_p2 = ((indvar_flatten40_fu_252 == 12'd1152) ? 1'b1 : 1'b0);

assign icmp_ln376_1_fu_1234_p2 = ((select_ln376_fu_1117_p3 == 7'd63) ? 1'b1 : 1'b0);

assign icmp_ln376_fu_621_p2 = ((indvar_flatten14_fu_244 == 11'd576) ? 1'b1 : 1'b0);

assign icmp_ln378_1_fu_1228_p2 = ((select_ln378_fu_1122_p3 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln378_fu_609_p2 = ((indvar_flatten_fu_236 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln380_1_fu_1036_p2 = ((add_ln380_fu_1030_p2 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln380_fu_817_p2 = ((kx_fu_228 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln380_mid213_fu_946_p2 = (not_exitcond_flatten_mid239_fu_936_p2 & icmp_ln380_mid235_fu_941_p2);

assign icmp_ln380_mid235_fu_941_p2 = (not_exitcond_flatten16_mid275_reg_1858 & icmp_ln380_mid267_fu_848_p2);

assign icmp_ln380_mid267_fu_848_p2 = (not_exitcond_flatten42_mid2121130_reg_1832 & and_ln368_fu_823_p2);

assign icmp_ln93_7_fu_1330_p2 = ((trunc_ln93_fu_1320_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_1324_p2 = ((tmp_25_fu_1310_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln96_7_fu_1378_p2 = ((trunc_ln96_fu_1368_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln96_fu_1372_p2 = ((tmp_27_fu_1358_p4 != 8'd255) ? 1'b1 : 1'b0);

assign kx_mid2_fu_974_p3 = ((empty_70_fu_969_p2[0:0] == 1'b1) ? 2'd0 : kx_fu_228);

assign ky_mid26_fu_903_p3 = ((empty_67_fu_897_p2[0:0] == 1'b1) ? 2'd0 : ky_fu_232);

assign lshr_ln18_fu_1532_p2 = zext_ln15_fu_1521_p1 >> zext_ln18_fu_1528_p1;

assign m_axi_gmem0_0_ARADDR = gmem0_addr_reg_1952;

assign m_axi_gmem0_0_ARBURST = 2'd0;

assign m_axi_gmem0_0_ARCACHE = 4'd0;

assign m_axi_gmem0_0_ARID = 1'd0;

assign m_axi_gmem0_0_ARLEN = 64'd576;

assign m_axi_gmem0_0_ARLOCK = 2'd0;

assign m_axi_gmem0_0_ARPROT = 3'd0;

assign m_axi_gmem0_0_ARQOS = 4'd0;

assign m_axi_gmem0_0_ARREGION = 4'd0;

assign m_axi_gmem0_0_ARSIZE = 3'd0;

assign m_axi_gmem0_0_ARUSER = 1'd0;

assign m_axi_gmem0_0_AWADDR = 64'd0;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = 32'd0;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_AWVALID = 1'b0;

assign m_axi_gmem0_0_BREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = 8'd0;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 1'd0;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign m_axi_gmem0_0_WVALID = 1'b0;

assign mantissa_fu_1512_p4 = {{{{1'd1}, {trunc_ln342_reg_2055}}}, {1'd0}};

assign not_exitcond_flatten16_mid275_fu_689_p2 = (exitcond_flatten16_mid275_fu_677_p2 ^ 1'd1);

assign not_exitcond_flatten42_mid2121130_fu_659_p2 = (icmp_ln370_fu_597_p2 | exitcond_flatten42_not131_fu_653_p2);

assign not_exitcond_flatten_mid239_fu_936_p2 = (exitcond_flatten_mid271_not_fu_931_p2 | exitcond_flatten16_mid275_reg_1843);

assign or_ln100_fu_1432_p2 = (icmp_ln100_fu_1420_p2 | icmp_ln100_7_fu_1426_p2);

assign or_ln368_1_fu_812_p2 = (icmp_ln370_reg_1809 | first_iter_1181_fu_806_p2);

assign or_ln368_fu_801_p2 = (icmp_ln370_reg_1809 | first_iter_2179_fu_795_p2);

assign or_ln93_fu_1336_p2 = (icmp_ln93_fu_1324_p2 | icmp_ln93_7_fu_1330_p2);

assign or_ln96_fu_1384_p2 = (icmp_ln96_fu_1372_p2 | icmp_ln96_7_fu_1378_p2);

assign output_r_address0 = output_r_address0_local;

assign output_r_ce0 = output_r_ce0_local;

assign output_r_d0 = select_ln108_fu_1681_p3;

assign output_r_we0 = output_r_we0_local;

assign p_shl11_fu_1192_p3 = {{add_ln310_17_fu_1186_p2}, {5'd0}};

assign p_shl_fu_1648_p4 = {{{tmp_s_fu_1638_p4}, {trunc_ln410_reg_1968_pp0_iter1_reg}}, {5'd0}};

assign q_15_fu_1348_p3 = ((and_ln93_fu_1342_p2[0:0] == 1'b1) ? 32'd1123942400 : q_reg_2024);

assign q_16_fu_1396_p3 = ((and_ln96_fu_1390_p2[0:0] == 1'b1) ? 32'd3271426048 : q_15_reg_2031);

assign qi_9_fu_1598_p3 = ((icmp_ln102_fu_1592_p2[0:0] == 1'b1) ? 32'd127 : result_fu_1576_p3);

assign reduce_bias_address0 = zext_ln368_fu_725_p1;

assign reduce_weight_scale_address0 = zext_ln368_fu_725_p1;

assign result_16_fu_1571_p2 = (32'd0 - val_reg_2070);

assign result_fu_1576_p3 = ((xs_sign_reg_2050[0:0] == 1'b1) ? result_16_fu_1571_p2 : val_reg_2070);

assign select_ln100_fu_1444_p3 = ((and_ln100_fu_1438_p2[0:0] == 1'b1) ? 32'd1056964608 : 32'd3204448256);

assign select_ln108_fu_1681_p3 = ((icmp_ln105_fu_1676_p2[0:0] == 1'b1) ? 8'd129 : trunc_ln108_reg_2081);

assign select_ln18_fu_1504_p3 = ((tmp_77_fu_1486_p3[0:0] == 1'b1) ? sext_ln18_fu_1500_p1 : add_ln317_fu_1480_p2);

assign select_ln368_3_fu_645_p3 = ((icmp_ln370_fu_597_p2[0:0] == 1'b1) ? add_ln368_fu_639_p2 : oc_fu_264);

assign select_ln368_fu_788_p3 = ((icmp_ln370_reg_1809[0:0] == 1'b1) ? 2'd0 : y_fu_256);

assign select_ln370_1_fu_753_p3 = ((icmp_ln370_fu_597_p2[0:0] == 1'b1) ? 13'd1 : add_ln370_1_fu_747_p2);

assign select_ln370_fu_853_p3 = ((and_ln368_3_reg_1824[0:0] == 1'b1) ? add_ln370_fu_828_p2 : select_ln368_fu_788_p3);

assign select_ln372_1_fu_1062_p3 = ((empty_63_fu_834_p2[0:0] == 1'b1) ? 12'd1 : add_ln372_1_reg_1890);

assign select_ln372_fu_1110_p3 = ((exitcond_flatten16_mid275_reg_1843[0:0] == 1'b1) ? add_ln372_fu_1104_p2 : x_mid247_fu_1097_p3);

assign select_ln376_2_fu_1055_p3 = ((empty_65_fu_860_p2[0:0] == 1'b1) ? 11'd1 : add_ln376_1_reg_1885);

assign select_ln376_fu_1117_p3 = ((exitcond_flatten_mid239_reg_1910[0:0] == 1'b1) ? add_ln376_reg_1915 : ic_mid221_reg_1905);

assign select_ln378_2_fu_1047_p3 = ((empty_67_fu_897_p2[0:0] == 1'b1) ? 4'd1 : add_ln378_1_fu_1042_p2);

assign select_ln378_fu_1122_p3 = ((icmp_ln380_mid213_reg_1929[0:0] == 1'b1) ? add_ln378_reg_1934 : ky_mid26_reg_1920);

assign sext_ln18_9_fu_1525_p1 = $signed(select_ln18_reg_2065);

assign sext_ln18_fu_1500_p1 = $signed(sub_ln18_fu_1494_p2);

assign sext_ln395_fu_1293_p1 = $signed(mul_ln396_fu_350_p2);

assign shl_ln18_fu_1538_p2 = zext_ln15_fu_1521_p1 << zext_ln18_fu_1528_p1;

assign sub_ln18_fu_1494_p2 = (8'd127 - xs_exp_fu_1464_p3);

assign tmp2_fu_1179_p3 = {{tmp_23_fu_1169_p4}, {trunc_ln410_reg_1968}};

assign tmp3_fu_1258_p3 = {{tmp_24_reg_1985}, {trunc_ln387_reg_1979}};

assign tmp_23_fu_1169_p4 = {{add_ln310_28_fu_1159_p2[11:1]}};

assign tmp_25_fu_1310_p4 = {{bitcast_ln93_fu_1307_p1[30:23]}};

assign tmp_27_fu_1358_p4 = {{bitcast_ln96_fu_1355_p1[30:23]}};

assign tmp_29_fu_1406_p4 = {{bitcast_ln100_fu_1403_p1[30:23]}};

assign tmp_31_fu_1689_p4 = {{add_ln372_4_fu_1670_p2[15:1]}};

assign tmp_39_fu_1544_p4 = {{lshr_ln18_fu_1532_p2[55:24]}};

assign tmp_40_fu_1554_p4 = {{shl_ln18_fu_1538_p2[55:24]}};

assign tmp_69_fu_707_p3 = {{select_ln368_3_fu_645_p3}, {6'd0}};

assign tmp_70_fu_1610_p3 = {{trunc_ln310_reg_1879_pp0_iter1_reg}, {5'd0}};

assign tmp_71_fu_1621_p3 = {{trunc_ln310_reg_1879_pp0_iter1_reg}, {3'd0}};

assign tmp_72_fu_1657_p4 = {{{tmp_s_fu_1638_p4}, {trunc_ln410_reg_1968_pp0_iter1_reg}}, {3'd0}};

assign tmp_73_fu_1135_p3 = {{trunc_ln310_3_fu_1131_p1}, {5'd0}};

assign tmp_74_fu_1147_p3 = {{trunc_ln310_3_fu_1131_p1}, {3'd0}};

assign tmp_75_fu_1200_p3 = {{add_ln310_17_fu_1186_p2}, {3'd0}};

assign tmp_77_fu_1486_p3 = add_ln317_fu_1480_p2[32'd8];

assign tmp_78_fu_1582_p4 = {{result_fu_1576_p3[31:7]}};

assign tmp_fu_695_p3 = {{select_ln368_3_fu_645_p3}, {9'd0}};

assign tmp_s_fu_1638_p4 = {{add_ln310_27_fu_1632_p2[10:1]}};

assign trunc_ln100_fu_1416_p1 = bitcast_ln100_fu_1403_p1[22:0];

assign trunc_ln108_fu_1606_p1 = qi_9_fu_1598_p3[7:0];

assign trunc_ln310_3_fu_1131_p1 = select_ln376_fu_1117_p3[5:0];

assign trunc_ln310_fu_731_p1 = select_ln368_3_fu_645_p3[4:0];

assign trunc_ln342_fu_1472_p1 = data_fu_1452_p1[22:0];

assign trunc_ln387_fu_1127_p1 = select_ln372_fu_1110_p3[0:0];

assign trunc_ln410_fu_1026_p1 = select_ln370_fu_853_p3[0:0];

assign trunc_ln93_fu_1320_p1 = bitcast_ln93_fu_1307_p1[22:0];

assign trunc_ln96_fu_1368_p1 = bitcast_ln96_fu_1355_p1[22:0];

assign val_fu_1564_p3 = ((tmp_77_reg_2060[0:0] == 1'b1) ? tmp_39_fu_1544_p4 : tmp_40_fu_1554_p4);

assign x_mid247_fu_1097_p3 = ((empty_63_reg_1895[0:0] == 1'b1) ? 2'd0 : x_fu_248);

assign xor_ln368_fu_603_p2 = (icmp_ln370_fu_597_p2 ^ 1'd1);

assign xs_exp_fu_1464_p3 = {{data_fu_1452_p1[30:23]}};

assign zext_ln15_fu_1521_p1 = mantissa_fu_1512_p4;

assign zext_ln18_fu_1528_p1 = $unsigned(sext_ln18_9_fu_1525_p1);

assign zext_ln304_fu_1255_p1 = kx_mid2_reg_1939;

assign zext_ln310_12_fu_1165_p1 = select_ln378_fu_1122_p3;

assign zext_ln310_19_fu_1628_p1 = tmp_71_fu_1621_p3;

assign zext_ln310_20_fu_1143_p1 = tmp_73_fu_1135_p3;

assign zext_ln310_21_fu_1155_p1 = tmp_74_fu_1147_p3;

assign zext_ln310_fu_1617_p1 = tmp_70_fu_1610_p3;

assign zext_ln317_fu_1476_p1 = xs_exp_fu_1464_p3;

assign zext_ln368_fu_725_p1 = select_ln368_3_fu_645_p3;

assign zext_ln372_fu_1666_p1 = tmp_72_fu_1657_p4;

assign zext_ln380_fu_1208_p1 = tmp_75_fu_1200_p3;

assign zext_ln383_fu_1270_p1 = add_ln310_fu_1264_p2;

assign zext_ln392_1_fu_1011_p1 = add_ln392_fu_1005_p2;

assign zext_ln392_2_fu_703_p1 = tmp_fu_695_p3;

assign zext_ln392_3_fu_715_p1 = tmp_69_fu_707_p3;

assign zext_ln392_fu_1002_p1 = add_ln392_2_reg_1864;

assign zext_ln409_fu_1706_p1 = add_ln310_s_fu_1699_p3;

always @ (posedge ap_clk) begin
    add_ln392_2_reg_1864[5:0] <= 6'b000000;
    select_ln100_reg_2045[30:0] <= 31'b0111111000000000000000000000000;
end

endmodule //restoration_top_conv3x3_valid_11
