-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity restoration_top_residual_block_tiled_2_Pipeline_VITIS_LOOP_488_4_VITIS_LOOP_490_5_VITIS_LOOP_492 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    add_ln504_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    zext_ln310_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    zext_ln488 : IN STD_LOGIC_VECTOR (3 downto 0);
    accumulator_1_out : OUT STD_LOGIC_VECTOR (24 downto 0);
    accumulator_1_out_ap_vld : OUT STD_LOGIC;
    tile_a_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    tile_a_ce0 : OUT STD_LOGIC;
    tile_a_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of restoration_top_residual_block_tiled_2_Pipeline_VITIS_LOOP_488_4_VITIS_LOOP_490_5_VITIS_LOOP_492 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_240 : STD_LOGIC_VECTOR (9 downto 0) := "1001000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln488_fu_208_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem0_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal zext_ln488_cast_fu_167_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln488_cast_reg_523 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln310_2_cast_fu_171_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln310_2_cast_reg_528 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln488_reg_533 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln488_reg_533_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln488_reg_533_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln488_reg_533_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln488_reg_533_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln488_reg_533_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal kx_mid2_fu_295_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal kx_mid2_reg_537 : STD_LOGIC_VECTOR (1 downto 0);
    signal kx_mid2_reg_537_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln490_fu_303_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln490_reg_542 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln310_fu_339_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln310_reg_547 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln492_2_fu_418_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln492_2_reg_552 : STD_LOGIC_VECTOR (16 downto 0);
    signal gmem0_addr_read_reg_562 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln495_fu_443_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal accumulator_1_fu_100 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    signal grp_fu_466_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_sig_allocacmp_accumulator_1_load : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal kx_fu_104 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln492_fu_345_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ky_fu_108 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal indvar_flatten_fu_112 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln490_1_fu_357_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ic_fu_116 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal select_ln488_fu_275_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten14_fu_120 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln488_1_fu_214_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten14_load : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp0 : BOOLEAN;
    signal tile_a_ce0_local : STD_LOGIC;
    signal icmp_ln490_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln492_fu_257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln486_fu_251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln488_fu_269_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln486_fu_243_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln486_fu_263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln490_fu_283_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln310_fu_311_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_315_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_4_fu_327_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln310_fu_323_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln310_3_fu_335_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln490_1_fu_351_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln310_6_fu_385_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln310_4_fu_389_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln310_7_fu_392_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_5_fu_406_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_shl_fu_398_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln492_fu_414_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln310_9_fu_433_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln304_fu_430_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln310_8_fu_437_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_466_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_149 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component restoration_top_mac_muladd_8s_8s_25s_25_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (24 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component restoration_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mac_muladd_8s_8s_25s_25_4_1_U140 : component restoration_top_mac_muladd_8s_8s_25s_25_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 25,
        dout_WIDTH => 25)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => gmem0_addr_read_reg_562,
        din1 => tile_a_q0,
        din2 => ap_sig_allocacmp_accumulator_1_load,
        ce => grp_fu_466_ce,
        dout => grp_fu_466_p3);

    flow_control_loop_pipe_sequential_init_U : component restoration_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    accumulator_1_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    accumulator_1_fu_100 <= ap_const_lv25_0;
                elsif ((ap_enable_reg_pp0_iter7 = ap_const_logic_1)) then 
                    accumulator_1_fu_100 <= grp_fu_466_p3;
                end if;
            end if; 
        end if;
    end process;

    ic_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_149)) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ic_fu_116 <= ap_const_lv7_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    ic_fu_116 <= select_ln488_fu_275_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten14_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln488_fu_208_p2 = ap_const_lv1_0))) then 
                    indvar_flatten14_fu_120 <= add_ln488_1_fu_214_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten14_fu_120 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_149)) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_112 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    indvar_flatten_fu_112 <= select_ln490_1_fu_357_p3;
                end if;
            end if; 
        end if;
    end process;

    kx_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_149)) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    kx_fu_104 <= ap_const_lv2_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    kx_fu_104 <= add_ln492_fu_345_p2;
                end if;
            end if; 
        end if;
    end process;

    ky_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_149)) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ky_fu_108 <= ap_const_lv2_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    ky_fu_108 <= select_ln490_fu_303_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                    add_ln310_reg_547(11 downto 3) <= add_ln310_fu_339_p2(11 downto 3);
                kx_mid2_reg_537 <= kx_mid2_fu_295_p3;
                select_ln490_reg_542 <= select_ln490_fu_303_p3;
                    zext_ln310_2_cast_reg_528(3 downto 0) <= zext_ln310_2_cast_fu_171_p1(3 downto 0);
                    zext_ln488_cast_reg_523(3 downto 0) <= zext_ln488_cast_fu_167_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                    add_ln492_2_reg_552(16 downto 3) <= add_ln492_2_fu_418_p2(16 downto 3);
                kx_mid2_reg_537_pp0_iter2_reg <= kx_mid2_reg_537;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln488_reg_533 <= icmp_ln488_fu_208_p2;
                icmp_ln488_reg_533_pp0_iter1_reg <= icmp_ln488_reg_533;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                icmp_ln488_reg_533_pp0_iter2_reg <= icmp_ln488_reg_533_pp0_iter1_reg;
                icmp_ln488_reg_533_pp0_iter3_reg <= icmp_ln488_reg_533_pp0_iter2_reg;
                icmp_ln488_reg_533_pp0_iter4_reg <= icmp_ln488_reg_533_pp0_iter3_reg;
                icmp_ln488_reg_533_pp0_iter5_reg <= icmp_ln488_reg_533_pp0_iter4_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                gmem0_addr_read_reg_562 <= m_axi_gmem0_0_RDATA;
            end if;
        end if;
    end process;
    zext_ln488_cast_reg_523(16 downto 4) <= "0000000000000";
    zext_ln310_2_cast_reg_528(11 downto 4) <= "00000000";
    add_ln310_reg_547(2 downto 0) <= "000";
    add_ln492_2_reg_552(2 downto 0) <= "000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    accumulator_1_out <= accumulator_1_fu_100;

    accumulator_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln488_reg_533_pp0_iter5_reg, ap_loop_exit_ready_pp0_iter6_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1) and (icmp_ln488_reg_533_pp0_iter5_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            accumulator_1_out_ap_vld <= ap_const_logic_1;
        else 
            accumulator_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln310_6_fu_385_p2 <= std_logic_vector(unsigned(zext_ln310_2_cast_reg_528) + unsigned(add_ln310_reg_547));
    add_ln310_7_fu_392_p2 <= std_logic_vector(unsigned(add_ln310_6_fu_385_p2) + unsigned(zext_ln310_4_fu_389_p1));
    add_ln310_8_fu_437_p2 <= std_logic_vector(unsigned(add_ln310_9_fu_433_p2) + unsigned(zext_ln304_fu_430_p1));
    add_ln310_9_fu_433_p2 <= std_logic_vector(unsigned(zext_ln488_cast_reg_523) + unsigned(add_ln492_2_reg_552));
    add_ln310_fu_339_p2 <= std_logic_vector(unsigned(zext_ln310_fu_323_p1) + unsigned(zext_ln310_3_fu_335_p1));
    add_ln488_1_fu_214_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten14_load) + unsigned(ap_const_lv10_1));
    add_ln488_fu_269_p2 <= std_logic_vector(unsigned(ic_fu_116) + unsigned(ap_const_lv7_1));
    add_ln490_1_fu_351_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_112) + unsigned(ap_const_lv4_1));
    add_ln490_fu_283_p2 <= std_logic_vector(unsigned(select_ln486_fu_243_p3) + unsigned(ap_const_lv2_1));
    add_ln492_2_fu_418_p2 <= std_logic_vector(unsigned(p_shl_fu_398_p3) + unsigned(zext_ln492_fu_414_p1));
    add_ln492_fu_345_p2 <= std_logic_vector(unsigned(kx_mid2_fu_295_p3) + unsigned(ap_const_lv2_1));
    and_ln486_fu_263_p2 <= (xor_ln486_fu_251_p2 and icmp_ln492_fu_257_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem0_0_RVALID)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_gmem0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem0_0_RVALID)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((m_axi_gmem0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem0_0_RVALID)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_gmem0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_149_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
                ap_condition_149 <= ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln488_fu_208_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln488_fu_208_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter6_reg, ap_done_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_accumulator_1_load_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_grp0, accumulator_1_fu_100, grp_fu_466_p3)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp0))) then 
            ap_sig_allocacmp_accumulator_1_load <= grp_fu_466_p3;
        else 
            ap_sig_allocacmp_accumulator_1_load <= accumulator_1_fu_100;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten14_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, indvar_flatten14_fu_120, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten14_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten14_load <= indvar_flatten14_fu_120;
        end if; 
    end process;

    empty_fu_289_p2 <= (icmp_ln490_fu_237_p2 or and_ln486_fu_263_p2);

    gmem0_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem0_0_RVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem0_blk_n_R <= m_axi_gmem0_0_RVALID;
        else 
            gmem0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_466_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            grp_fu_466_ce <= ap_const_logic_1;
        else 
            grp_fu_466_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln488_fu_208_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten14_load = ap_const_lv10_240) else "0";
    icmp_ln490_fu_237_p2 <= "1" when (indvar_flatten_fu_112 = ap_const_lv4_9) else "0";
    icmp_ln492_fu_257_p2 <= "1" when (kx_fu_104 = ap_const_lv2_3) else "0";
    kx_mid2_fu_295_p3 <= 
        ap_const_lv2_0 when (empty_fu_289_p2(0) = '1') else 
        kx_fu_104;
    m_axi_gmem0_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem0_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem0_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem0_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_0_BREADY <= ap_const_logic_0;

    m_axi_gmem0_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_gmem0_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem0_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_0_WDATA <= ap_const_lv8_0;
    m_axi_gmem0_0_WID <= ap_const_lv1_0;
    m_axi_gmem0_0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_0_WSTRB <= ap_const_lv1_0;
    m_axi_gmem0_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_WVALID <= ap_const_logic_0;
    p_shl_fu_398_p3 <= (add_ln310_7_fu_392_p2 & ap_const_lv5_0);
    select_ln486_fu_243_p3 <= 
        ap_const_lv2_0 when (icmp_ln490_fu_237_p2(0) = '1') else 
        ky_fu_108;
    select_ln488_fu_275_p3 <= 
        add_ln488_fu_269_p2 when (icmp_ln490_fu_237_p2(0) = '1') else 
        ic_fu_116;
    select_ln490_1_fu_357_p3 <= 
        ap_const_lv4_1 when (icmp_ln490_fu_237_p2(0) = '1') else 
        add_ln490_1_fu_351_p2;
    select_ln490_fu_303_p3 <= 
        add_ln490_fu_283_p2 when (and_ln486_fu_263_p2(0) = '1') else 
        select_ln486_fu_243_p3;
    tile_a_address0 <= zext_ln495_fu_443_p1(17 - 1 downto 0);
    tile_a_ce0 <= tile_a_ce0_local;

    tile_a_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            tile_a_ce0_local <= ap_const_logic_1;
        else 
            tile_a_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_4_fu_327_p3 <= (trunc_ln310_fu_311_p1 & ap_const_lv3_0);
    tmp_5_fu_406_p3 <= (add_ln310_7_fu_392_p2 & ap_const_lv3_0);
    tmp_fu_315_p3 <= (trunc_ln310_fu_311_p1 & ap_const_lv5_0);
    trunc_ln310_fu_311_p1 <= select_ln488_fu_275_p3(6 - 1 downto 0);
    xor_ln486_fu_251_p2 <= (icmp_ln490_fu_237_p2 xor ap_const_lv1_1);
    zext_ln304_fu_430_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kx_mid2_reg_537_pp0_iter2_reg),17));
    zext_ln310_2_cast_fu_171_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln310_2),12));
    zext_ln310_3_fu_335_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_327_p3),12));
    zext_ln310_4_fu_389_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln490_reg_542),12));
    zext_ln310_fu_323_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_315_p3),12));
    zext_ln488_cast_fu_167_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln488),17));
    zext_ln492_fu_414_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_406_p3),17));
    zext_ln495_fu_443_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln310_8_fu_437_p2),64));
end behav;
