-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity restoration_top_res1_3_conv1_bias_ROM_1P_LUTRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of restoration_top_res1_3_conv1_bias_ROM_1P_LUTRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111100100100000101011111100110", 1 => "10111101011100011101111110000110", 2 => "10111100111111111101101110111010", 3 => "00111100101010001011001101110110", 
    4 => "00111100101100110000001110101111", 5 => "00111101000110011010010010001110", 6 => "00111100100001110010000001100100", 7 => "00111100110101001110111100011000", 
    8 => "10111011100111110101011111000001", 9 => "10111101011010011000011111011111", 10 => "00111101010011010011011001111111", 11 => "00111100111011111111010111011010", 
    12 => "10111101010001101001011001010100", 13 => "10111011110010100110101101101111", 14 => "00111011000110011001101100100110", 15 => "10111101000000001001110110100101", 
    16 => "10111100001101100100010111111010", 17 => "10111100111010111001010101110011", 18 => "10111101100001000011110000000100", 19 => "00111100011001010111011001010110", 
    20 => "00111101000010000000010001111010", 21 => "00111101001001100110111001001001", 22 => "10111100110110011110001010111000", 23 => "00111100111001100000011110010111", 
    24 => "00111011110110000101111100101100", 25 => "10111100010001100111010110111001", 26 => "10111101010100111100010111111101", 27 => "10111101001000000010001000100000", 
    28 => "10111101001101011111001010001000", 29 => "10111100111110111100001001000100", 30 => "00111011110101010000101010110100", 31 => "10111100100100111001110001001110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "distributed"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "distributed";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

