-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity restoration_top_res1_1_conv2_bias_ROM_1P_LUTRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of restoration_top_res1_1_conv2_bias_ROM_1P_LUTRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111100110101011010101111010101", 1 => "00111011111101000000100010100101", 2 => "10111100001110101100100010000100", 3 => "10111101000001010100001011111110", 
    4 => "00111101011101000101100101010101", 5 => "10111011010101010100101100100101", 6 => "10111100001110101001010101000000", 7 => "00111101010000001000111111101100", 
    8 => "00111101011000000000100001011001", 9 => "00111101001100101100110000010011", 10 => "10111101000000101011010111100000", 11 => "10111101000011011110100011001111", 
    12 => "10111100101001011110010110100100", 13 => "10111101000000111101100110101111", 14 => "10111101001110100001001100000011", 15 => "00111011100110100101010001111011", 
    16 => "10111100010111111000101000001100", 17 => "00111101010110100110110010111010", 18 => "10111100010111010101011000000011", 19 => "00111010011001101100111001100011", 
    20 => "10111011101100001100010101011011", 21 => "00111011101001101010110011001111", 22 => "10111011110000011111110111001000", 23 => "00111101000110110011111011001010", 
    24 => "10111100110111110001110111001000", 25 => "10111100111001010111010100110011", 26 => "10111101011110011001000010001001", 27 => "10111100111110101000111001011111", 
    28 => "10111100111111000011100101001100", 29 => "00111100111010000111010111010010", 30 => "10111001110001111110000011110111", 31 => "10111100100011010010100011100111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "distributed"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "distributed";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

