-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity restoration_top_res1_0_conv2_bias_ROM_1P_LUTRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of restoration_top_res1_0_conv2_bias_ROM_1P_LUTRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101001001101100100000011010", 1 => "00111101000001010111011001001000", 2 => "10111101000011111000101000110000", 3 => "00111100011011110010010010100101", 
    4 => "10111101010111000011110010001010", 5 => "10111100000101000110111010111000", 6 => "10111101000100111100001100100111", 7 => "10111101000101001011011001011011", 
    8 => "00111100101001101100100100111010", 9 => "10111101000100011100101111110111", 10 => "00111101001010000001100111100111", 11 => "10111100011110010010100001111001", 
    12 => "00111101011111110100101110100100", 13 => "10111101000100011111100100001100", 14 => "10111100011010101111110111110000", 15 => "10111100011001110110010011100010", 
    16 => "00111100110011001101111000000000", 17 => "10111101010101000101110110011111", 18 => "00111100100110001110101010011011", 19 => "10111101000010011100000001000110", 
    20 => "00111100111101110010011110100000", 21 => "00111011011010111000001101001100", 22 => "10111100110000011111111111101001", 23 => "10111011100100100011010101001111", 
    24 => "00111101010101011111100010000000", 25 => "00111101011100001111111101110000", 26 => "00111100011101011011001100101011", 27 => "10111101001111100110010011000001", 
    28 => "10111100110100011111001111000111", 29 => "10111100110111111000011110011111", 30 => "10111011110010100101011110011101", 31 => "10111101000101111001001010101100");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "distributed"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "distributed";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

