-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity restoration_top_res1_2_conv1_bias_ROM_1P_LUTRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of restoration_top_res1_2_conv1_bias_ROM_1P_LUTRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101011010000110100000100101", 1 => "00111011000110101010010111001111", 2 => "00111101001100101101000100100111", 3 => "10111101010001010010010001000100", 
    4 => "10111101000100011101001001001011", 5 => "10111101001010000110101000110111", 6 => "10111010101011000111010000001011", 7 => "10111101000101100000010011110001", 
    8 => "00111100100010100010010001111000", 9 => "10111101001100100101111110001111", 10 => "10111101001101000010110011101100", 11 => "00111101001110110101101110101101", 
    12 => "00111100000010111001111011111111", 13 => "00111100111010111001010101100001", 14 => "00111101100110000001100011110111", 15 => "10111011110101010001001010010111", 
    16 => "10111101011100011000011100001011", 17 => "10111100000100110001011000101000", 18 => "00111101001000101110101010000110", 19 => "00111100100011100001110100100000", 
    20 => "00111100111001010101001001001010", 21 => "10111100001011101100001101000110", 22 => "10111101001111010110011111110110", 23 => "10111100100011110100111001101101", 
    24 => "10111101010010001000101110010010", 25 => "10111100101100010001001000011100", 26 => "00111101001010111110011011111011", 27 => "00111101010111000001011010000000", 
    28 => "00111100111011110110000111111001", 29 => "00111101000010000110110001101100", 30 => "00111100000011110001111110100101", 31 => "00111010100000100000111000111000");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "distributed"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "distributed";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

