-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity restoration_top_res1_3_conv2_weight_scale_ROM_1P_LUTRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of restoration_top_res1_3_conv2_weight_scale_ROM_1P_LUTRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111010010100111100101111110010", 1 => "00111010010110111010000111010111", 2 => "00111010100000100011000011010111", 3 => "00111010000111110011001111111101", 
    4 => "00111010011111000110000111010000", 5 => "00111010100111110101111010110101", 6 => "00111010001000111100101100000100", 7 => "00111010100110110100111010001011", 
    8 => "00111010010110010111101101101110", 9 => "00111010011101001111001100110001", 10 => "00111010001101000001001100101010", 11 => "00111010100000000110111100010101", 
    12 => "00111010100011011001010101101110", 13 => "00111010001011111011001111011100", 14 => "00111010010000001001011001000101", 15 => "00111010101101010011000000111101", 
    16 => "00111010011100101000110011101011", 17 => "00111010001100011111011111011101", 18 => "00111010100000101110011110010010", 19 => "00111010011100110111100100011111", 
    20 => "00111010011000101011110011100010", 21 => "00111010010011101001111110100011", 22 => "00111010100000011000101001110111", 23 => "00111010011101110000101010010001", 
    24 => "00111010100001110101100111111001", 25 => "00111010100101100010110000011001", 26 => "00111010010101001100011100001000", 27 => "00111010011110111001010100000001", 
    28 => "00111010100000100001101000001100", 29 => "00111010001100110101100101011010", 30 => "00111010001010100100111100111011", 31 => "00111010100000010011111001011000");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "distributed"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "distributed";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

