-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity restoration_top_res1_1_conv2_weight_scale_ROM_1P_LUTRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of restoration_top_res1_1_conv2_weight_scale_ROM_1P_LUTRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111010111100100101101101110101", 1 => "00111010110010011100111111011110", 2 => "00111010111111001101000001011011", 3 => "00111010110011100000101101111100", 
    4 => "00111010011001101011111100010101", 5 => "00111010100110011110100110101010", 6 => "00111011000101001011000110010100", 7 => "00111011000100111101000010101000", 
    8 => "00111010100110101011101010001000", 9 => "00111011001001110011001101010110", 10 => "00111010111111110110110111101011", 11 => "00111011001100001100011001011101", 
    12 => "00111011000001110010001101000001", 13 => "00111011010010011010001010010000", 14 => "00111010100111011010011101010111", 15 => "00111010010101101011010101000010", 
    16 => "00111010110101000011101010001001", 17 => "00111011000100101110111011011100", 18 => "00111010110010011101101110011011", 19 => "00111011000000101001110010011011", 
    20 => "00111010111011011010001001001011", 21 => "00111010111110110000001111101000", 22 => "00111010101011111111100100000001", 23 => "00111011000100011101100011111001", 
    24 => "00111010110000110100110100111110", 25 => "00111010110000110010000010100100", 26 => "00111010011110100010011010111110", 27 => "00111010101010001001100110011001", 
    28 => "00111011011110100001111010100110", 29 => "00111010110101101011011101100101", 30 => "00111010111110101001110001001010", 31 => "00111010110000001000110100110001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "distributed"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "distributed";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

