-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity restoration_top_conv3x3_valid_11_reduce_bias_ROM_1P_LUTRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of restoration_top_conv3x3_valid_11_reduce_bias_ROM_1P_LUTRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101000110011000111101000101", 1 => "00111100101101110010100101001000", 2 => "00111100001110110111001111110111", 3 => "10111101000010010110110100100001", 
    4 => "10111100111001100100000110111010", 5 => "10111101001010011011000110001010", 6 => "10111100101110001100000000001001", 7 => "00111101000001111000010111100001", 
    8 => "10111011010000000011011001111111", 9 => "00111100000001000101010101000100", 10 => "10111100111111000000100001100101", 11 => "10111101000001110010111101101101", 
    12 => "00111011111010010100011101001110", 13 => "10111100111001110011101001001011", 14 => "10111100101111101001101010011110", 15 => "00111100110111110100100111110110", 
    16 => "00111100010011010111110001011110", 17 => "10111100110101100010101101010111", 18 => "10111100101011100011010111000001", 19 => "10111101000011110110001111111010", 
    20 => "00111101000001110011011100101101", 21 => "10111101001000100100010011010111", 22 => "10111100100011000011011110110001", 23 => "00111100110011100101111010000011", 
    24 => "00111100111111101101001100110111", 25 => "00111000000101011100011001101100", 26 => "00111100100111011010100001011011", 27 => "10111101000101000001010110100111", 
    28 => "00111101001100010011110110110101", 29 => "10111100000000110001100110111100", 30 => "10111011010110110111000000011000", 31 => "00111100110101111101110000110001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "distributed"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "distributed";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

