-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity restoration_top_conv3x3_valid_11_reduce_weight_scale_ROM_1P_LUTRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of restoration_top_conv3x3_valid_11_reduce_weight_scale_ROM_1P_LUTRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111010001010101110001100101110", 1 => "00111010000011000010100001101111", 2 => "00111010001000111101101011001011", 3 => "00111010001000010111011101111001", 
    4 => "00111001111000110001101111001110", 5 => "00111001110100100101111011100110", 6 => "00111010000011110110101011010110", 7 => "00111010000010100001011010100100", 
    8 => "00111001111101100101110101001110", 9 => "00111001111000000011001101001101", 10 => "00111001110100110111001111000001", 11 => "00111010001111110011011011000001", 
    12 => "00111001110100110010000000011100", 13 => "00111001110101011000011011011101", 14 => "00111010000011100100101100110001", 15 => "00111010000110011001010100001011", 
    16 => "00111001110110101111010001011101", 17 => "00111001111100001011110111100101", 18 => "00111001111001001100000101110001", 19 => "00111010001111011001111011001010", 
    20 => "00111001111011000001010001101011", 21 => "00111001110011010111011111010011", 22 => "00111001110111100101101110100011", 23 => "00111010000001011101110000001100", 
    24 => "00111001111100001100011010010011", 25 => "00111001110101000111111010100111", 26 => "00111001110011101001000110010001", 27 => "00111010010011100110010101011100", 
    28 => "00111001111011000011011110100100", 29 => "00111010000000010111110111010011", 30 => "00111001111110101011110011011110", 31 => "00111001110111001100001100001010");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "distributed"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "distributed";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

