-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity restoration_top_head_weight_scale_ROM_1P_LUTRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of restoration_top_head_weight_scale_ROM_1P_LUTRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111011001010100011111101000111", 1 => "00111011001000100011001011110101", 2 => "00111011000011000111011110100011", 3 => "00111011001010011001000000111010", 
    4 => "00111011001010110001000101010110", 5 => "00111011000011101000001101001011", 6 => "00111011001011100001000010000010", 7 => "00111011001010111101001001010101", 
    8 => "00111011001010011011010010011000", 9 => "00111011001010100100010100101100", 10 => "00111011001010110110011101110101", 11 => "00111011001001100010010011011011", 
    12 => "00111011000100000001010010101010", 13 => "00111011001001101100000001001011", 14 => "00111011001000110000100110000111", 15 => "00111011001000010100000101000111", 
    16 => "00111011000110010101001011001000", 17 => "00111011000110101000000110001010", 18 => "00111011000101000110111110010101", 19 => "00111011001010010000010011100111", 
    20 => "00111011000100010110001111101101", 21 => "00111011000110111101111111111000", 22 => "00111011001001111011011011111001", 23 => "00111011000000001101110111001010", 
    24 => "00111011001001110011101110111001", 25 => "00111011000100100100111100100010", 26 => "00111011000111110011111101101100", 27 => "00111011000011111001101111111110", 
    28 => "00111011000000110110111100011010", 29 => "00111011000111100000001001011110", 30 => "00111011000010011111100111000111", 31 => "00111011000011001110100101101110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "distributed"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "distributed";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

