-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity restoration_top_res1_0_conv1_weight_scale_ROM_1P_LUTRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of restoration_top_res1_0_conv1_weight_scale_ROM_1P_LUTRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111010000010101001100011101001", 1 => "00111010010010100011111101101100", 2 => "00111010011001000100000101000011", 3 => "00111010000000101011101101110110", 
    4 => "00111010001100110100101111110100", 5 => "00111010000110000001010001000001", 6 => "00111010001111000010000010101010", 7 => "00111010110110110111100110111001", 
    8 => "00111010000111110001100000011011", 9 => "00111010010111000100100110000100", 10 => "00111010001100000011001000000011", 11 => "00111010000101001111100011011100", 
    12 => "00111010000111101100110111000110", 13 => "00111010000101110100100010110010", 14 => "00111010010110101111100100010101", 15 => "00111010001001100100000011001001", 
    16 => "00111010100011110001111110001111", 17 => "00111010100001000100011001010110", 18 => "00111010000010100000001001011000", 19 => "00111010010000000100001100111110", 
    20 => "00111010010001011101000110000000", 21 => "00111010001011001001101010010001", 22 => "00111010001111010001110011000100", 23 => "00111010010010101111001001100000", 
    24 => "00111010001100110111100001100011", 25 => "00111010100100010110011011100110", 26 => "00111010011010011101110101100000", 27 => "00111010001010011111001101100010", 
    28 => "00111010100011100101000101001100", 29 => "00111010001011000011011100101000", 30 => "00111010001000100100000100111101", 31 => "00111010100100101011111011100110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "distributed"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "distributed";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

