-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity restoration_top_res1_3_conv1_weight_scale_ROM_1P_LUTRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of restoration_top_res1_3_conv1_weight_scale_ROM_1P_LUTRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111010010001110101101010010100", 1 => "00111001111111111101010111010011", 2 => "00111010000110110010111011011100", 3 => "00111010010000100110011100010110", 
    4 => "00111010010011001010000011001111", 5 => "00111010000010111001100000100010", 6 => "00111010000010100111101111001101", 7 => "00111010011100100111011011100111", 
    8 => "00111010001111101100110010100000", 9 => "00111010011001101011100111111101", 10 => "00111010000100101101000100000011", 11 => "00111010000010011010100100000111", 
    12 => "00111010000011000011110101001010", 13 => "00111010001110010001011011111011", 14 => "00111010000100101011000011000110", 15 => "00111001111110111011111000101000", 
    16 => "00111010001100010010111111011000", 17 => "00111010001101110100010100111011", 18 => "00111010010010110011000101100110", 19 => "00111010001001000111000110100000", 
    20 => "00111010100001010100010010011000", 21 => "00111010001000001011100100011110", 22 => "00111010000001100010101011010111", 23 => "00111010000010111001011110001101", 
    24 => "00111010000100111111001101011010", 25 => "00111010000110100101110110000010", 26 => "00111010000111011010000100111010", 27 => "00111010000010010100001110101110", 
    28 => "00111010001010000111001000001100", 29 => "00111010000011001111010110101101", 30 => "00111010001001010011100010100100", 31 => "00111010010001101010011111000100");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "distributed"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "distributed";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

