-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity restoration_top_conv3x3_valid_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    weights : IN STD_LOGIC_VECTOR (63 downto 0);
    weight_scale_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    weight_scale_ce0 : OUT STD_LOGIC;
    weight_scale_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    bias_ce0 : OUT STD_LOGIC;
    bias_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    in_channels : IN STD_LOGIC_VECTOR (6 downto 0);
    input_size : IN STD_LOGIC_VECTOR (4 downto 0);
    input_scale : IN STD_LOGIC_VECTOR (31 downto 0);
    output_scale : IN STD_LOGIC_VECTOR (31 downto 0);
    idx2 : IN STD_LOGIC_VECTOR (18 downto 0);
    tile_a_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    tile_a_ce0 : OUT STD_LOGIC;
    tile_a_we0 : OUT STD_LOGIC;
    tile_a_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of restoration_top_conv3x3_valid_1 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_322BCC77 : STD_LOGIC_VECTOR (31 downto 0) := "00110010001010111100110001110111";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal bound43_fu_143_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal reg_261 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal bound75_fu_134_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal output_size_fu_399_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal output_size_reg_515 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln368_fu_421_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln368_reg_521 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln368_fu_427_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln368_reg_526 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_fu_439_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal empty_reg_533 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal select_ln88_fu_493_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln88_reg_560 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_44_fu_501_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_44_reg_565 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_start : STD_LOGIC;
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_done : STD_LOGIC;
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_idle : STD_LOGIC;
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_ready : STD_LOGIC;
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWVALID : STD_LOGIC;
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_WVALID : STD_LOGIC;
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_WLAST : STD_LOGIC;
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARVALID : STD_LOGIC;
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_RREADY : STD_LOGIC;
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_BREADY : STD_LOGIC;
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_input_r_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_input_r_ce0 : STD_LOGIC;
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_weight_scale_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_weight_scale_ce0 : STD_LOGIC;
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_bias_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_bias_ce0 : STD_LOGIC;
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_tile_a_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_tile_a_ce0 : STD_LOGIC;
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_tile_a_we0 : STD_LOGIC;
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_tile_a_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal bound75_fu_134_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal bound75_fu_134_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal bound43_fu_143_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal bound43_fu_143_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_80_fu_409_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln368_fu_417_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln88_fu_405_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal bound43_cast_fu_447_p0 : STD_LOGIC_VECTOR (14 downto 0);
    signal bitcast_ln88_fu_452_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_455_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln88_fu_465_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln88_1_fu_475_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_fu_469_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln88_fu_481_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln88_fu_487_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal bound43_fu_143_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal bound43_fu_143_p10 : STD_LOGIC_VECTOR (14 downto 0);
    signal bound75_fu_134_p00 : STD_LOGIC_VECTOR (17 downto 0);
    signal bound75_fu_134_p10 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component restoration_top_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_WREADY : IN STD_LOGIC;
        m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RVALID : IN STD_LOGIC;
        m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem0_0_RLAST : IN STD_LOGIC;
        m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
        m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_BVALID : IN STD_LOGIC;
        m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        tmp_45 : IN STD_LOGIC_VECTOR (23 downto 0);
        input_r_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        in_channels : IN STD_LOGIC_VECTOR (6 downto 0);
        input_scale : IN STD_LOGIC_VECTOR (31 downto 0);
        select_ln88 : IN STD_LOGIC_VECTOR (31 downto 0);
        bound75 : IN STD_LOGIC_VECTOR (17 downto 0);
        bound43 : IN STD_LOGIC_VECTOR (13 downto 0);
        mul_ln368 : IN STD_LOGIC_VECTOR (9 downto 0);
        zext_ln368_2 : IN STD_LOGIC_VECTOR (9 downto 0);
        weights : IN STD_LOGIC_VECTOR (63 downto 0);
        idx2_cast : IN STD_LOGIC_VECTOR (18 downto 0);
        weight_scale_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        weight_scale_ce0 : OUT STD_LOGIC;
        weight_scale_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        bias_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        bias_ce0 : OUT STD_LOGIC;
        bias_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        zext_ln368 : IN STD_LOGIC_VECTOR (9 downto 0);
        tile_a_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        tile_a_ce0 : OUT STD_LOGIC;
        tile_a_we0 : OUT STD_LOGIC;
        tile_a_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component restoration_top_mul_5ns_15ns_18_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component restoration_top_mul_5ns_11ns_15_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component restoration_top_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364 : component restoration_top_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_start,
        ap_done => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_done,
        ap_idle => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_idle,
        ap_ready => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_ready,
        m_axi_gmem0_0_AWVALID => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY => ap_const_logic_0,
        m_axi_gmem0_0_AWADDR => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY => ap_const_logic_0,
        m_axi_gmem0_0_WDATA => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY => m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID => m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA => m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST => m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID => m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM => m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER => m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP => m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID => ap_const_logic_0,
        m_axi_gmem0_0_BREADY => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP => ap_const_lv2_0,
        m_axi_gmem0_0_BID => ap_const_lv1_0,
        m_axi_gmem0_0_BUSER => ap_const_lv1_0,
        tmp_45 => tmp_44_reg_565,
        input_r_address0 => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_input_r_address0,
        input_r_ce0 => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_input_r_ce0,
        input_r_q0 => input_r_q0,
        in_channels => in_channels,
        input_scale => input_scale,
        select_ln88 => select_ln88_reg_560,
        bound75 => reg_261,
        bound43 => empty_reg_533,
        mul_ln368 => trunc_ln368_reg_526,
        zext_ln368_2 => trunc_ln368_reg_526,
        weights => weights,
        idx2_cast => idx2,
        weight_scale_address0 => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_weight_scale_address0,
        weight_scale_ce0 => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_weight_scale_ce0,
        weight_scale_q0 => weight_scale_q0,
        bias_address0 => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_bias_address0,
        bias_ce0 => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_bias_ce0,
        bias_q0 => bias_q0,
        zext_ln368 => trunc_ln368_reg_526,
        tile_a_address0 => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_tile_a_address0,
        tile_a_ce0 => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_tile_a_ce0,
        tile_a_we0 => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_tile_a_we0,
        tile_a_d0 => grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_tile_a_d0);

    mul_5ns_15ns_18_1_1_U121 : component restoration_top_mul_5ns_15ns_18_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 15,
        dout_WIDTH => 18)
    port map (
        din0 => bound75_fu_134_p0,
        din1 => bound75_fu_134_p1,
        dout => bound75_fu_134_p2);

    mul_5ns_11ns_15_1_1_U122 : component restoration_top_mul_5ns_11ns_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 11,
        dout_WIDTH => 15)
    port map (
        din0 => bound43_fu_143_p0,
        din1 => bound43_fu_143_p1,
        dout => bound43_fu_143_p2);

    fcmp_32ns_32ns_1_2_no_dsp_1_U123 : component restoration_top_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => output_scale,
        din1 => ap_const_lv32_322BCC77,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_4,
        dout => grp_fu_393_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_ready = ap_const_logic_1)) then 
                    grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    reg_261_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                reg_261 <= bound75_fu_134_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                reg_261 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bound43_fu_143_p2),18));
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                add_ln368_reg_521 <= add_ln368_fu_421_p2;
                output_size_reg_515 <= output_size_fu_399_p2;
                trunc_ln368_reg_526 <= trunc_ln368_fu_427_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                empty_reg_533 <= empty_fu_439_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                select_ln88_reg_560 <= select_ln88_fu_493_p3;
                    tmp_44_reg_565(23 downto 6) <= tmp_44_fu_501_p3(23 downto 6);
            end if;
        end if;
    end process;
    tmp_44_reg_565(5 downto 0) <= "000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_done, ap_CS_fsm_state5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln368_fu_421_p2 <= std_logic_vector(unsigned(zext_ln368_fu_417_p1) + unsigned(zext_ln88_fu_405_p1));
    and_ln88_fu_487_p2 <= (or_ln88_fu_481_p2 and grp_fu_393_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_done)
    begin
        if ((grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_done, ap_CS_fsm_state5)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_done = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_done, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bias_address0 <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_bias_address0;
    bias_ce0 <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_bias_ce0;
    bitcast_ln88_fu_452_p1 <= output_scale;
    bound43_cast_fu_447_p0 <= reg_261(15 - 1 downto 0);
    bound43_fu_143_p0 <= bound43_fu_143_p00(5 - 1 downto 0);
    bound43_fu_143_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(output_size_reg_515),15));
    bound43_fu_143_p1 <= bound43_fu_143_p10(11 - 1 downto 0);
    bound43_fu_143_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln368_reg_521),15));
    bound75_fu_134_p0 <= bound75_fu_134_p00(5 - 1 downto 0);
    bound75_fu_134_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(output_size_reg_515),18));
    bound75_fu_134_p1 <= bound75_fu_134_p10(15 - 1 downto 0);
    bound75_fu_134_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bound43_cast_fu_447_p0),18));
    empty_fu_439_p1 <= bound43_fu_143_p2(14 - 1 downto 0);
    grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_start <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_ap_start_reg;
    icmp_ln88_1_fu_475_p2 <= "1" when (trunc_ln88_fu_465_p1 = ap_const_lv23_0) else "0";
    icmp_ln88_fu_469_p2 <= "0" when (tmp_s_fu_455_p4 = ap_const_lv8_FF) else "1";
    input_r_address0 <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_input_r_address0;
    input_r_ce0 <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_input_r_ce0;
    m_axi_gmem0_0_ARADDR <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARADDR;
    m_axi_gmem0_0_ARBURST <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARBURST;
    m_axi_gmem0_0_ARCACHE <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARCACHE;
    m_axi_gmem0_0_ARID <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARID;
    m_axi_gmem0_0_ARLEN <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARLEN;
    m_axi_gmem0_0_ARLOCK <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARLOCK;
    m_axi_gmem0_0_ARPROT <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARPROT;
    m_axi_gmem0_0_ARQOS <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARQOS;
    m_axi_gmem0_0_ARREGION <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARREGION;
    m_axi_gmem0_0_ARSIZE <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARSIZE;
    m_axi_gmem0_0_ARUSER <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARUSER;
    m_axi_gmem0_0_ARVALID <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_ARVALID;
    m_axi_gmem0_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_0_BREADY <= ap_const_logic_0;
    m_axi_gmem0_0_RREADY <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_m_axi_gmem0_0_RREADY;
    m_axi_gmem0_0_WDATA <= ap_const_lv8_0;
    m_axi_gmem0_0_WID <= ap_const_lv1_0;
    m_axi_gmem0_0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_0_WSTRB <= ap_const_lv1_0;
    m_axi_gmem0_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_WVALID <= ap_const_logic_0;
    or_ln88_fu_481_p2 <= (icmp_ln88_fu_469_p2 or icmp_ln88_1_fu_475_p2);
    output_size_fu_399_p2 <= std_logic_vector(unsigned(input_size) + unsigned(ap_const_lv5_1E));
    select_ln88_fu_493_p3 <= 
        ap_const_lv32_322BCC77 when (and_ln88_fu_487_p2(0) = '1') else 
        output_scale;
    tile_a_address0 <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_tile_a_address0;
    tile_a_ce0 <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_tile_a_ce0;
    tile_a_d0 <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_tile_a_d0;
    tile_a_we0 <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_tile_a_we0;
    tmp_44_fu_501_p3 <= (reg_261 & ap_const_lv6_0);
    tmp_80_fu_409_p3 <= (in_channels & ap_const_lv3_0);
    tmp_s_fu_455_p4 <= bitcast_ln88_fu_452_p1(30 downto 23);
    trunc_ln368_fu_427_p1 <= add_ln368_fu_421_p2(10 - 1 downto 0);
    trunc_ln88_fu_465_p1 <= bitcast_ln88_fu_452_p1(23 - 1 downto 0);
    weight_scale_address0 <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_weight_scale_address0;
    weight_scale_ce0 <= grp_conv3x3_valid_1_Pipeline_VITIS_LOOP_368_1_VITIS_LOOP_370_2_VITIS_LOOP_372_3_VITI_fu_364_weight_scale_ce0;
    zext_ln368_fu_417_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_80_fu_409_p3),11));
    zext_ln88_fu_405_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_channels),11));
end behav;
