-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity restoration_top_res1_2_conv2_bias_ROM_1P_LUTRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of restoration_top_res1_2_conv2_bias_ROM_1P_LUTRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101000100010000110010100000", 1 => "10111101001100110001101100010110", 2 => "10111100101101100100010111001101", 3 => "00111100110000101000000000110100", 
    4 => "10111101000111001100001101001100", 5 => "00111101000101001001010001110011", 6 => "00111011100110000001100101010000", 7 => "10111101000000110101011101100010", 
    8 => "00111100001110011111100101000010", 9 => "10111011000010111111100000010000", 10 => "00111101000010110100101011101111", 11 => "10111011111001110011000011111111", 
    12 => "00111101010101111011000001100000", 13 => "10111011100010001010101101111011", 14 => "00111011111111010001011101001111", 15 => "00111100011101100111111110001010", 
    16 => "10111101011011001001000011011101", 17 => "00111100010000000000110011001100", 18 => "10111101011100011110000100011100", 19 => "10111100110111101010001100100010", 
    20 => "00111100010111111111111000100101", 21 => "10111100101110111111001011101111", 22 => "00111100110110010010111111101101", 23 => "00111100010000001001000010010000", 
    24 => "00111100101101000010001001101111", 25 => "10111100010111001110100110011100", 26 => "10111100001011011100011000110011", 27 => "00111100010011011100001110110011", 
    28 => "00111011010010110011000000000011", 29 => "10111101000010010011100100101011", 30 => "10111101011010010110001110000001", 31 => "00111100100001111101011010000100");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "distributed"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "distributed";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

