-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity restoration_top_res1_1_conv1_bias_ROM_1P_LUTRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of restoration_top_res1_1_conv1_bias_ROM_1P_LUTRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101001010000010101011100010", 1 => "00111101001011100101100010100010", 2 => "10111100010100011000101000100010", 3 => "00111011101110111100010010010110", 
    4 => "00111101010001000111110000101100", 5 => "10111100100000111001111110001001", 6 => "10111100110100000001111111010010", 7 => "00111011100111101100101100000000", 
    8 => "00111010100000101110101111010001", 9 => "10111100010111000000010010011110", 10 => "00111101001000100100101111110101", 11 => "10111100101001011111000000110101", 
    12 => "00111100001100001011101111010110", 13 => "00111101000100001100000111010100", 14 => "10111101010010011011100010001100", 15 => "10111101000011101001010100011001", 
    16 => "10111101001110001111100101100111", 17 => "10111101010000000101110101100001", 18 => "10111100000110011000000110010011", 19 => "00111101001010001111101111111010", 
    20 => "00111011101110000000000011001101", 21 => "10111100000111101001011101100000", 22 => "10111100100101011011000101110111", 23 => "00111101001101111001000111011000", 
    24 => "00111101000101000001000111010110", 25 => "10111011101000110001000101100000", 26 => "00111101001110000011000100110011", 27 => "10111100100100001000000110000010", 
    28 => "10111100110010111101001011001000", 29 => "10111100110011101100011011101001", 30 => "10111100101011110100001111111100", 31 => "00111100100111011010101000100001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "distributed"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "distributed";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

